  DROP TABLE TMP_SENT_WK;
CREATE TABLE TMP_SENT_WK AS
SELECT SENDID        AS ID_SEND
     , EMAILADDRESS  AS DS_MAIL 
  FROM SERBINOC.TB_EXACT_SENT
 WHERE SENDID IN (100814,100820,100821,100984,102430,102431,104825,105990,108902) 
   AND TO_DATE(EVENTDATE,'DD/MM/YY') >= TO_DATE('09/08/19','DD/MM/YY')
 GROUP BY SENDID
     , EMAILADDRESS;
     
  DROP TABLE TMP_OPEN_WK;
CREATE TABLE TMP_OPEN_WK AS
SELECT SENDID        AS ID_SEND
     , EMAILADDRESS  AS DS_MAIL
     , MIN(TO_DATE(EVENTDATE,'DD/MM/YY'))DT_EVEN 
  FROM SERBINOC.TB_EXACT_OPENS
 WHERE SENDID IN (100814,100820,100821,100984,102430,102431,104825,105990,108902)
   AND TO_DATE(EVENTDATE,'DD/MM/YY') >= TO_DATE('09/08/19','DD/MM/YY')
 GROUP BY SENDID
     , EMAILADDRESS;

  DROP TABLE TMP_CLIQ_WK;
CREATE TABLE TMP_CLIQ_WK AS
SELECT SENDID        AS ID_SEND
     , EMAILADDRESS  AS DS_MAIL
     , MIN(TO_DATE(EVENTDATE,'DD/MM/YY'))DT_EVEN
  FROM SERBINOC.TB_EXACT_CLICKS
 WHERE SENDID IN (100814,100820,100821,100984,102430,102431,104825,105990,108902)
   AND TO_DATE(EVENTDATE,'DD/MM/YY') >= TO_DATE('09/08/19','DD/MM/YY')
 GROUP BY SENDID
     , EMAILADDRESS; 

 DROP TABLE TMP_COMN;
CREATE TABLE TMP_COMN AS -- SELECT * FROM TMP_COMN
SELECT A.DS_MAIL
     , A.ID_SEND
     , CASE WHEN B.DS_MAIL IS NULL THEN 0 ELSE 1 END AS FG_OPEN
     , B.DT_EVEN AS DT_OPEN
     , CASE WHEN C.DS_MAIL IS NULL THEN 0 ELSE 1 END AS FG_CLIC
     , C.DT_EVEN AS DT_CLIC
  FROM TMP_SENT_WK A
  LEFT JOIN TMP_OPEN_WK B
    ON A.DS_MAIL = B.DS_MAIL
   AND A.ID_SEND = B.ID_SEND
  LEFT JOIN TMP_CLIQ_WK C
    ON A.DS_MAIL = C.DS_MAIL
   AND A.ID_SEND = C.ID_SEND;

UPDATE TMP_COMN
   SET DT_OPEN = DT_CLIC
 WHERE FG_CLIC = 1 AND FG_OPEN = 0; COMMIT;

UPDATE TMP_COMN
   SET FG_OPEN = 1
 WHERE FG_CLIC = 1 AND FG_OPEN = 0; COMMIT;
 
  DROP TABLE TMP_COMN_UNIQ; 
CREATE TABLE TMP_COMN_UNIQ AS
SELECT DS_MAIL
     , COUNT(*)QT_COMN
     , MAX(FG_OPEN)FG_OPEN
     , MIN(DT_OPEN)DT_OPEN
     , MAX(FG_CLIC)FG_CLIC
     , MIN(DT_CLIC)DT_CLIC
  FROM TMP_COMN
 GROUP BY DS_MAIL;
  
/* 
1. RECEBERAM PELO MENOS UMA DAS COMUNICACOES
2. ABRIU PELO MENOS UMA
3. CLICOU EM PELO MENOS UMA*/

SELECT COUNT(*)QT, FG_OPEN, FG_CLIC
  FROM TMP_COMN_UNIQ -- 91891
 GROUP BY FG_OPEN, FG_CLIC
 ORDER BY 2,3
  
/*
4. INTERAGIU E GEROU LEAD
*/  

SELECT COUNT(DISTINCT A.DS_MAIL)
  FROM TMP_COMN A 
 INNER JOIN TAB_LEAD_TMP B
    ON UPPER(A.DS_MAIL) = UPPER(B.EMAIL)
   AND TO_DATE(DATA_CRIACAO,'DD/MM/YY') >= TO_DATE(A.DT_OPEN, 'DD/MM/YY')
   
/*
5. LEAD GERADO NO MESMO DIA DO CLIQUE
*/      
  
SELECT COUNT(DISTINCT A.DS_MAIL)
  FROM TMP_COMN A -- select * from TAB_LEAD_TMP
 INNER JOIN TAB_LEAD_TMP B
    ON UPPER(A.DS_MAIL) = UPPER(B.EMAIL)
   AND TO_DATE(DATA_CRIACAO,'DD/MM/YY') = TO_DATE(A.DT_CLIC, 'DD/MM/YY')
   
/*
6. QUANTAS COMUNICACOES ATE GERAR LEAD
*/    

SELECT COUNT(*), QT_COMN
  FROM (
SELECT A.DS_MAIL, COUNT(DISTINCT A.ID_SEND)QT_COMN
  FROM TMP_COMN A -- select * from TAB_LEAD_TMP
 INNER JOIN TAB_LEAD_TMP B
    ON UPPER(A.DS_MAIL) = UPPER(B.EMAIL)
   AND TO_DATE(DATA_CRIACAO,'DD/MM/YY') >= TO_DATE(A.DT_OPEN, 'DD/MM/YY')
 GROUP BY A.DS_MAIL)
 GROUP BY QT_COMN
 ORDER BY 2
 

/*
7. LEAD GERADO POR DISPARO
*/    

SELECT COUNT(*), ID_SEND FROM (
SELECT COUNT(DISTINCT A.DS_MAIL) DS_MAIL
     , MIN(A.ID_SEND) ID_SEND
  FROM TMP_COMN A -- select * from TAB_LEAD_TMP
 INNER JOIN TAB_LEAD_TMP B
    ON UPPER(A.DS_MAIL) = UPPER(B.EMAIL)
   AND TO_DATE(DATA_CRIACAO,'DD/MM/YY') >= TO_DATE(A.DT_OPEN, 'DD/MM/YY')
 GROUP BY A.DS_MAIL) GROUP BY ID_SEND
 ORDER BY 1 DESC
 