
--CRIANDO TABELA UNIFICADA 

CREATE TABLE TMP_DBM_TRAN_FULL AS 
SELECT CD_CHAS FROM TAB_PROC_DBM_TRAN
WHERE TO_DATE(DT_COMP,'DD/MM/YY') >= TO_DATE('01/01/2015','DD/MM/YYYY')

UNION

SELECT CD_CHAS FROM TAB_PROC_DBM_TRAN_COMP
WHERE TO_DATE(DT_COMP,'DD/MM/YY') >= TO_DATE('01/01/2015','DD/MM/YYYY')
;COMMIT

--VINS EM COMUM 

CREATE TABLE TMP_SCA_BASE_ANALISE_COMUM AS
SELECT A.VIN_CODE 
FROM TMP_SCA_BASE_ANALISE A
INNER JOIN TMP_DBM_TRAN_FULL B
 ON  A.VIN_CODE = B.CD_CHAS;
;COMMIT

--SO NA DELES

 CREATE TABLE TMP_SCA_BASE_ANALISE_DELES AS
SELECT A.VIN_CODE 
FROM TMP_SCA_BASE_ANALISE A
LEFT JOIN TMP_DBM_TRAN_FULL B
 ON  A.VIN_CODE = B.CD_CHAS
WHERE B.CD_CHAS IS NULL;
;COMMIT

--SO NA NOSSA

CREATE TABLE TMP_SCA_BASE_ANALISE_NOSSA AS
SELECT A.CD_CHAS
FROM TMP_DBM_TRAN_FULL A
LEFT JOIN TMP_SCA_BASE_ANALISE B
 ON  A.CD_CHAS = B.VIN_CODE
WHERE B.VIN_CODE IS NULL;
COMMIT;
