--ANALISE DE CONVERSÃO DE LEADS MUSTANG

DELETE FROM TMP_LEADS_MUSTANG WHERE CPF IS NULL OR REPLACE(TRANSLATE(CPF, '1234567890', ' '),' ','') IS NOT NULL

CREATE TABLE TMP_POS_LEAD_MUSTANG AS
SELECT CAST (I.CPF AS NUMERIC) CPF
,I.PRIMEIRO_NOME
,I.DT_CRIACAO AS DT_CRIACAO_LEAD
,I.VEICULO_INTERESSE 
,I.LEAD_ID
,A.DT_COMP 
,A.DS_MODL_ESPC AS MODELO_COMPRADO
,ID_DEAL AS DEALER_COMPRA
,CASE WHEN A.DS_MODL_RESM IS NOT NULL THEN 'Y' 
      WHEN A.DS_MODL_RESM IS NULL THEN 'N'
      END AS LEAD_CONVERTIDO
,ROW_NUMBER() OVER(PARTITION BY I.LEAD_ID ORDER BY A.DT_COMP DESC) NR_SEQC
FROM TMP_LEADS_MUSTANG I 
LEFT JOIN TAB_PROC_DBM_TRAN A
ON CAST (I.CPF AS NUMERIC) = A.NR_CPF 
AND TO_DATE(A.DT_COMP,'DD/MM/YY') BETWEEN TO_DATE(I.DT_CRIACAO ,'DD/MM/YYYY') AND TO_DATE(I.DT_CRIACAO ,'DD/MM/YYYY') + 90   
AND A.DS_MODL_RESM = 'MUSTANG'

--TOP DEALERS

SELECT DEALER_COMPRA, COUNT(*)
FROM TMP_POS_LEAD_MUSTANG 
WHERE DEALER_COMPRA IS NOT NULL
GROUP BY DEALER_COMPRA
ORDER BY  COUNT(*) DESC







