--ATUALIZAÇÃO TABELA DE USER
DROP TABLE TAB_PROC_DBM_TRAN;COMMIT;
CREATE TABLE TAB_PROC_DBM_TRAN AS
SELECT CAST(I.CPF AS NUMERIC)AS NR_CPF
     , DTPURCHASE            AS DT_COMP
     , VR.IDVEHICLE          AS ID_VEIC
     , VF.DSVIN              AS CD_CHAS
     , VF.CDTMA              AS CD_TMA
     , VF.CDSEQ              AS CD_SEQC
     , MM.DSORIGINALMODEL    AS DS_MODL_ESPC
     , MM.DSMODEL            AS DS_MODL
     , V.NBMODELYEAR         AS DS_MODL_ANO
     , D.MODELO_BIA          AS DS_MODL_RESM
	 , VR.IDDEALER 	 	     AS ID_DEAL
     , DP.DSMOTOR            AS DS_MOTR
     , E.DSCOLOR             AS DS_COR
     , ROW_NUMBER() OVER(PARTITION BY CAST(I.CPF AS NUMERIC) ORDER BY DTPURCHASE DESC) NR_SEQC
     , ROW_NUMBER() OVER(PARTITION BY VF.DSVIN ORDER BY DTPURCHASE DESC) NR_SEQC_CHAS
  FROM FORD.INDIVIDUAL               I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER 
 INNER JOIN FORD.VEHICLEFACT         VF
    ON VR.IDVEHICLE = VF.IDVEHICLE 
 INNER JOIN FORD.VEHICLE             V
    ON VF.IDVEHICLE = V.IDVEHICLE 
 INNER JOIN FORD.MAKERMODEL          MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN TAB_PROC_DEPARA_DASH     D
    ON VF.CDTMA = D.CDTMA
  LEFT JOIN FORD.MOTOR               DP
    ON VF.TPMOTOR = DP.TPMOTOR
  LEFT JOIN FORD.VEHICLECOLOR        E
    ON VF.IDCOLOR = E.IDCOLOR
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2000','DD/MM/YYYY') AND TO_DATE('31/12/2025','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL;
  COMMIT;
  
  --VENDAS
SELECT COUNT(*), DT_COMP, ID_DEAL
  FROM TAB_PROC_DBM_TRAN
  WHERE DT_COMP>='24/03/20'
  GROUP BY DT_COMP, ID_DEAL
  ORDER BY 2,3

  --SHEET 1 PRIMEIRA FILEIRA,VERIFICAR SE NAO TEM DIA SEM VENDA E SE VALORES BATEM ANTES

SELECT  DT_COMP,COUNT(*)
  FROM TAB_PROC_DBM_TRAN
  WHERE DT_COMP>='24/03/20'
  GROUP BY DT_COMP
  ORDER BY 1

 --SHEET 1 SEGUNDA FILEIRA,VERIFICAR SE NAO TEM DIA SEM VENDA E SE VALORES BATEM ANTES

SELECT ID_DEAL,COUNT(*)
  FROM TAB_PROC_DBM_TRAN
  WHERE DT_COMP>='24/03/20'
  GROUP BY ID_DEAL
  ORDER BY 1
 

--ADICIONAR VALOR NA LATERAL E JOGAR O COMPRE SEM  SAIR DE CASA E O WEB NAS RESPECTIVAS COLUNAS,SO O VALOR DO DIA ANTERIOR (NAO ATUALIZA NENHUMA LINHA DE ANTES)
 SELECT COUNT(*)
      , CASE WHEN ORIGEM_DO_LEAD = 'Compre sem sair de casa' THEN 'Compre sem sair de casa'  ELSE 'WEB' END ORIGEM
      , TO_DATE(DATA_DE_CRIAÇÃO, 'DD/MM/YYYY')
   FROM   STG_PROC_LEAD_B A
   WHERE TO_DATE(DATA_DE_CRIAÇÃO, 'DD/MM/YYYY') > '29/05/20'
     AND (SUB_ORIGEM IN ('Website','Hotsite','Facebook','Ford Credit','Linkedin','Instagram','Ford Sempre','Website - KMI','Icarros','Olx') 
      OR ORIGEM_DO_LEAD = 'Compre sem sair de casa')
   GROUP BY CASE WHEN ORIGEM_DO_LEAD = 'Compre sem sair de casa'  THEN 'Compre sem sair de casa'  ELSE 'WEB' END
      , TO_DATE(DATA_DE_CRIAÇÃO, 'DD/MM/YYYY')
      ORDER BY 2,3 



 --SHEET LEAD CONVERTIDO

 SELECT *
   FROM (
   SELECT A.ORIGEM_DO_LEAD
        , SUB_ORIGEM
        , CATÁLOGO
        , TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY')
        , NOME_DA_CONCESSIONÁRIA
        , CPF
        , B.DT_COMP
        , B.DS_MODL
        , CD_CHAS
        , A.ID_PRINCIPAL
        , B.ID_DEAL
        , ROW_NUMBER() OVER(PARTITION BY CD_CHAS ORDER BY TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY') DESC)NRSEQC
   FROM   STG_PROC_LEAD_B A
   INNER JOIN TAB_PROC_DBM_TRAN B
     ON CAST(A.CPF AS NUMERIC) = B.NR_CPF
     AND B.DT_COMP >= TO_DATE(A.DATA_DE_CRIAÇÃO,'DD/MM/YYYY')
 WHERE REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL
     AND (SUB_ORIGEM IN ('Website','Hotsite','Facebook','Ford Credit','Linkedin','Instagram','Ford Sempre','Website - KMI','Icarros','Olx') 
      OR ORIGEM_DO_LEAD = 'Compre sem sair de casa'))
     WHERE NRSEQC = 1
    ORDER BY 4


-- VERIFICAR HISTORICO RETROATIVO DE WEB E COMPRE SEM SAIR DE CASA E VER SE BATE COM OS QUE ESTAO NA TABELA,PODEM TER DIAS SEM VENDA,VERIFICAR NA QUERY SE ESTA BATENDO OS VALORES TOTAIS COM O DO EXCEL ANTES PARA POUPAR TRABALHO
--LEMBRAR DE ADICIONAR DATAS NOVAS(AS DO DIA ANTERIOR)
--FAZER VLOOKUP COM DATAS PARA VERIFICAR QUAIS LINHAS PRECISAM SER ATUALIZADAS
 SELECT COUNT(*), ORIGEM_DO_LEAD,DATA
   FROM (
   SELECT A.ORIGEM_DO_LEAD
        , SUB_ORIGEM
        , CATÁLOGO
        , TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY')DATA
        , NOME_DA_CONCESSIONÁRIA
        , CPF
        , B.DT_COMP
        , B.DS_MODL
        , ROW_NUMBER() OVER(PARTITION BY CD_CHAS ORDER BY TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY') DESC)NRSEQC
   FROM   STG_PROC_LEAD_B A
   INNER JOIN TAB_PROC_DBM_TRAN B
     ON CAST(A.CPF AS NUMERIC) = B.NR_CPF
     AND B.DT_COMP >= TO_DATE(A.DATA_DE_CRIAÇÃO,'DD/MM/YYYY')
     WHERE REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL
     AND (SUB_ORIGEM IN ('Website','Hotsite','Facebook','Ford Credit','Linkedin','Instagram','Ford Sempre','Website - KMI','Icarros','Olx') 
     OR ORIGEM_DO_LEAD = 'Compre sem sair de casa'))
     WHERE NRSEQC = 1
     GROUP BY ORIGEM_DO_LEAD,DATA
     ORDER BY 2,3 