

--TABELA AUXILIAR ULTIMA COMPRA USUARIO
CREATE TABLE AUX_ULT_COMP_AUTOBUSCA AS
SELECT EMAIL
,MAX(TO_DATE(SUBSTR (CREATED_AT, 1, 10),'DD/MM/YYYY'))  FG_ULT_COMP
FROM TMP_PEDIDOS_AUTO_BUSCA
GROUP BY EMAIL
;COMMIT;

--TABELA MEDIA VALOR DE COMPRA USUARIO
CREATE TABLE AUX_AVG_COMP_AUTOBUSCA AS
SELECT EMAIL
,AVG(TOTAL) FG_TICKET_MEDIO
FROM TMP_PEDIDOS_AUTO_BUSCA
GROUP BY EMAIL
;COMMIT;

--TABELA FINAL
DROP TABLE TMP_CLIENTE_AUTO_BUSCA_FINAL ;COMMIT;
CREATE TABLE TMP_CLIENTE_AUTO_BUSCA_FINAL AS 
SELECT A.*
,B.FG_ULT_COMP
,C.FG_TICKET_MEDIO
,CASE WHEN D.EMAIL IS NULL THEN 0
      ELSE 1
      END AS FG_COMPRA
FROM TMP_CLIENTES_AUTO_BUSCA A 
LEFT JOIN AUX_ULT_COMP_AUTOBUSCA B
ON LOWER(A.EMAIL) = LOWER(B.EMAIL)
LEFT JOIN AUX_AVG_COMP_AUTOBUSCA C
ON LOWER(A.EMAIL) = LOWER(C.EMAIL)
LEFT JOIN TMP_PEDIDOS_AUTO_BUSCA D
ON LOWER(A.EMAIL) = LOWER(D.EMAIL)
;COMMIT;

DROP TABLE AUX_AVG_COMP_AUTOBUSCA;COMMIT;
DROP TABLE AUX_ULT_COMP_AUTOBUSCA;COMMIT;
