
--BASE
 DROP TABLE TMP_PROC_DBM_COMP;
CREATE TABLE TMP_PROC_DBM_COMP AS
SELECT I.IDCOMPANY  AS ID_COMP
  FROM FORD.COMPANY I 
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDCOMPANY = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE 
 INNER JOIN FORD.VEHICLE     V
    ON VF.IDVEHICLE = V.IDVEHICLE 
 INNER JOIN FORD.MAKERMODEL  MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 WHERE (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
 AND MM.DSMAKER = 'FORD'
   AND SUBSTR(VR.DTPURCHASE, 7,2) < 25;   

--NOME
  DROP TABLE TMP_PROC_DBM_NOME_COMP; 
CREATE TABLE TMP_PROC_DBM_NOME_COMP AS
SELECT I.NMCOMPANY          AS DS_NOME
     , CAST(I.CNPJ AS NUMERIC)  AS NR_CNPJ
     , CASE WHEN OP.ID_INDV IS NULL THEN 0 ELSE 1 END  AS FG_OPTO
     , ROW_NUMBER() OVER(PARTITION BY CAST(I.CNPJ AS NUMERIC) ORDER BY I.DTLASTUPDATE DESC) AS NR_SEQC
  FROM FORD.COMPANY           I 
 INNER JOIN TMP_PROC_DBM_COMP D
    ON I.IDCOMPANY = D.ID_COMP
  LEFT JOIN TMP_OPTO          OP
    ON I.IDCOMPANY = OP.ID_INDV
  LEFT JOIN FORD.INDIVIDUALSTANDARDDEMOGRAPHICS B
    ON  I.IDCOMPANY = B.IDINDIVIDUAL
 WHERE REPLACE(TRANSLATE(I.CNPJ, '1234567890', ' '),' ','') IS NULL;   
COMMIT;

DELETE FROM TMP_PROC_DBM_NOME_COMP
 WHERE NR_SEQC <> 1; COMMIT;


--EMAIL

 DROP TABLE TMP_PROC_DBM_MAIL_COMP; COMMIT;
CREATE TABLE TMP_PROC_DBM_MAIL_COMP AS
SELECT CAST(A.CNPJ AS NUMERIC) AS NR_CNPJ
     , A.IDCOMPANY   AS ID_COMP
     , LOWER(B.DSEMAIL) AS DS_MAIL
     , 0 AS FG_INTR
     , 0 AS FG_INTR_12M
     , 0 AS FG_INTR_18M
     , 0 AS FG_INTR_24M
     , ROW_NUMBER() OVER(PARTITION BY CAST(A.CNPJ AS NUMERIC) ORDER BY B.DTLASTUPDATE DESC) AS NR_SEQC
  FROM FORD.COMPANY          A 
 INNER JOIN FORD.EMAIL       B  
    ON A.IDCOMPANY = B.IDPERSON
 INNER JOIN TMP_PROC_DBM_COMP D
    ON A.IDCOMPANY = D.ID_COMP
 WHERE DBMTOOLS.ISEMAIL(DSEMAIL) = 1  AND DSEMAIL LIKE '%@%.%'
   AND DSEMAIL NOT LIKE '%@ford%'     AND DSEMAIL NOT LIKE '%@naote%'
   AND DSEMAIL NOT LIKE '%@nao%'      AND DSEMAIL NOT LIKE '%@test%'
   AND DSEMAIL NOT LIKE '%@asd%'      AND DSEMAIL NOT LIKE '%@.com%'
   AND DSEMAIL NOT LIKE '%@xxx%'      AND DSEMAIL NOT LIKE '%hahaha%'
   AND DSEMAIL NOT LIKE '%tenho%'     AND DSEMAIL NOT LIKE '%/%'
   AND DSEMAIL NOT LIKE '%(%'         AND DSEMAIL NOT LIKE '%,%'
   AND DSEMAIL NOT LIKE '%;%'         AND DSEMAIL NOT LIKE '%\%'
   AND DSEMAIL NOT LIKE '%.@%'        AND DSEMAIL NOT LIKE '%@.%'
   AND DSEMAIL NOT LIKE '% %'         AND DSEMAIL NOT LIKE '%nao%te%'
   AND DSEMAIL NOT LIKE '%@com%'      AND DSEMAIL NOT LIKE '%veic%'
   AND DSEMAIL NOT LIKE '%auto%'      AND DSEMAIL NOT LIKE '%ford%'
   AND DSEMAIL NOT LIKE '%venda%'     AND DSEMAIL NOT LIKE '%atendimento%'
   AND DSEMAIL NOT LIKE '%combr'      AND DSEMAIL NOT LIKE '%possu%'
   AND DSEMAIL NOT LIKE 'nao%'        AND DSEMAIL NOT LIKE '%test%' 
   AND REPLACE(TRANSLATE(A.CNPJ, '1234567890', ' '),' ','') IS NULL;

DELETE FROM TMP_PROC_DBM_MAIL_COMP
 WHERE NR_SEQC <> 1;
COMMIT;

UPDATE TMP_PROC_DBM_MAIL_COMP 
   SET FG_INTR = 1
 WHERE LOWER(DS_MAIL) IN 
        (SELECT LOWER(EMAILADDRESS) AS EMAIL
           FROM SERBINOC.TB_EXACT_OPENS A
          GROUP BY LOWER(EMAILADDRESS));COMMIT;

UPDATE TMP_PROC_DBM_MAIL_COMP 
   SET FG_INTR_12M = 1
 WHERE LOWER(DS_MAIL) IN 
        (SELECT LOWER(EMAILADDRESS) AS EMAIL
           FROM SERBINOC.TB_EXACT_OPENS A
          WHERE MONTHS_BETWEEN (SYSDATE,EVENTDATE) <= 12
          GROUP BY LOWER(EMAILADDRESS));COMMIT;

UPDATE TMP_PROC_DBM_MAIL_COMP 
   SET FG_INTR_18M = 1
 WHERE LOWER(DS_MAIL) IN 
        (SELECT LOWER(EMAILADDRESS) AS EMAIL
           FROM SERBINOC.TB_EXACT_OPENS A
          WHERE MONTHS_BETWEEN (SYSDATE,EVENTDATE) <= 18
          GROUP BY LOWER(EMAILADDRESS));COMMIT;

UPDATE TMP_PROC_DBM_MAIL_COMP 
   SET FG_INTR_24M = 1
 WHERE LOWER(DS_MAIL) IN 
        (SELECT LOWER(EMAILADDRESS) AS EMAIL
           FROM SERBINOC.TB_EXACT_OPENS A
          WHERE MONTHS_BETWEEN (SYSDATE,EVENTDATE) <= 24
          GROUP BY LOWER(EMAILADDRESS));COMMIT;


--TELEFONE

  DROP TABLE TMP_PROC_DBM_TELF_COMP; COMMIT; 
CREATE TABLE TMP_PROC_DBM_TELF_COMP AS
SELECT CAST(A.CNPJ AS NUMERIC)  AS NR_CNPJ
     , A.IDCOMPANY  AS ID_COMP
     , CASE WHEN TPTELEPHONE = 'M' THEN 'CELULAR' ELSE 'FIXO' END AS DS_TP_TELF
     , B.NBAREACODE     AS NR_DDD_TELF
     , B.NBTELEPHONE    AS NR_TELF
     , ROW_NUMBER() OVER(PARTITION BY CAST(A.CNPJ AS NUMERIC), CASE WHEN TPTELEPHONE = 'M' THEN 'CELULAR' ELSE 'FIXO' END ORDER BY B.DTLASTUPDATE DESC) AS NR_SEQC
  FROM FORD.COMPANY           A 
 INNER JOIN FORD.TELEPHONE    B  
    ON A.IDCOMPANY = B.IDPERSON
 INNER JOIN TMP_PROC_DBM_COMP D
    ON A.IDCOMPANY = D.ID_COMP
 WHERE TPTELEPHONE <> 'I'
   AND REPLACE(TRANSLATE(A.CNPJ, '1234567890', ' '),' ','') IS NULL;  
    
COMMIT;

DELETE FROM TMP_PROC_DBM_TELF_COMP
 WHERE NR_SEQC <> 1;COMMIT;
 
DELETE FROM TMP_PROC_DBM_TELF_COMP
 WHERE LENGTH(NR_DDD_TELF) <> 2
    OR LENGTH(NR_TELF) NOT BETWEEN 8 AND 9
    OR SUBSTR(NR_TELF,1,1) = 1
    OR NR_DDD_TELF = SUBSTR(NR_TELF,1,2);COMMIT;

DELETE FROM TMP_PROC_DBM_TELF_COMP
 WHERE SUBSTR(NR_TELF, 3,1) IN ('5','6','7','8','9')
   AND DS_TP_TELF <> 'CELULAR'; COMMIT;
   
DELETE FROM TMP_PROC_DBM_TELF_COMP
 WHERE SUBSTR(NR_TELF, 3,1) NOT IN ('5','6','7','8','9')
   AND DS_TP_TELF = 'CELULAR'; COMMIT;
   
DELETE FROM TMP_PROC_DBM_TELF_COMP
 WHERE LENGTH(NR_TELF) <> 8
   AND DS_TP_TELF <> 'CELULAR'; COMMIT;
   
UPDATE TMP_PROC_DBM_TELF_COMP
   SET NR_TELF = '9'||NR_TELF
 WHERE DS_TP_TELF = 'CELULAR'
   AND LENGTH(NR_TELF) = 8;COMMIT;
   

--ENDERECO

  DROP TABLE TMP_PROC_DBM_ENDR_COMP; COMMIT; 
CREATE TABLE TMP_PROC_DBM_ENDR_COMP AS
SELECT CAST(A.CNPJ AS NUMERIC) AS NR_CNPJ
     , A.IDCOMPANY   AS ID_COMP
     , B.TPSTREET       AS DS_TP_LOGR
     , B.DSADDRESS      AS DS_LOGR
     , B.NBADDRESS      AS DS_NUMR
     , B.DSCOMPLEMENT   AS DS_COMP
     , B.NMDISTRICT     AS DS_BAIR
     , B.NBPOSTALCODE   AS CD_CEP
     , B.DSCITY         AS DS_CIDD
     , B.CDSTATE        AS DS_UF
     , ROW_NUMBER() OVER(PARTITION BY CAST(A.CNPJ AS NUMERIC) ORDER BY B.DTLASTUPDATE DESC) AS NR_SEQC
     , 1                AS FG_VALD
  FROM FORD.COMPANY       A 
 INNER JOIN FORD.ADDRESS     B  
    ON A.IDCOMPANY = B.IDPERSON
 INNER JOIN TMP_PROC_DBM_COMP D
    ON A.IDCOMPANY = D.ID_COMP
 WHERE REPLACE(TRANSLATE(A.CNPJ, '1234567890', ' '),' ','') IS NULL;

DELETE FROM TMP_PROC_DBM_ENDR_COMP
 WHERE NR_SEQC <> 1;

UPDATE TMP_PROC_DBM_ENDR_COMP
   SET FG_VALD = 0
 WHERE ((DS_UF = 'AC' AND CD_CEP NOT LIKE '699%')
    OR  (DS_UF = 'AL' AND CD_CEP NOT LIKE '57%')
    OR  (DS_UF = 'AM' AND (CD_CEP NOT LIKE '690%' AND CD_CEP NOT LIKE '691%' AND CD_CEP NOT LIKE '692%' AND CD_CEP NOT LIKE '694%' AND CD_CEP NOT LIKE '695%' AND CD_CEP NOT LIKE '696%' AND CD_CEP NOT LIKE '697%' AND CD_CEP NOT LIKE '698%'))
    OR  (DS_UF = 'AP' AND CD_CEP NOT LIKE '689%')
    OR  (DS_UF = 'BA' AND (CD_CEP NOT LIKE '40%' AND CD_CEP NOT LIKE '41%' AND CD_CEP NOT LIKE '42%' AND CD_CEP NOT LIKE '43%' AND CD_CEP NOT LIKE '44%' AND CD_CEP NOT LIKE '45%' AND CD_CEP NOT LIKE '46%' AND CD_CEP NOT LIKE '47%' AND CD_CEP NOT LIKE '48%'))
    OR  (DS_UF = 'CE' AND (CD_CEP NOT LIKE '60%' AND CD_CEP NOT LIKE '61%' AND CD_CEP NOT LIKE '62%' AND CD_CEP NOT LIKE '63%'))
    OR  (DS_UF = 'DF' AND (CD_CEP NOT LIKE '70%' AND CD_CEP NOT LIKE '71%' AND CD_CEP NOT LIKE '72%' AND CD_CEP NOT LIKE '73%'))
    OR  (DS_UF = 'ES' AND CD_CEP NOT LIKE '29%')
    OR  (DS_UF = 'GO' AND (CD_CEP NOT LIKE '72%' AND CD_CEP NOT LIKE '73%' AND CD_CEP NOT LIKE '74%' AND CD_CEP NOT LIKE '75%' AND CD_CEP NOT LIKE '76%'))
    OR  (DS_UF = 'MA' AND CD_CEP NOT LIKE '65%')
    OR  (DS_UF = 'MG' AND CD_CEP NOT LIKE '3%')
    OR  (DS_UF = 'MS' AND CD_CEP NOT LIKE '79%')
    OR  (DS_UF = 'MT' AND (CD_CEP NOT LIKE '780%' AND CD_CEP NOT LIKE '781%' AND CD_CEP NOT LIKE '782%' AND CD_CEP NOT LIKE '783%' AND CD_CEP NOT LIKE '784%' AND CD_CEP NOT LIKE '785%' AND CD_CEP NOT LIKE '786%' AND CD_CEP NOT LIKE '787%' AND CD_CEP NOT LIKE '788%'))
    OR  (DS_UF = 'PA' AND (CD_CEP NOT LIKE '66%' AND CD_CEP NOT LIKE '67%' AND CD_CEP NOT LIKE '68%'))
    OR  (DS_UF = 'PB' AND CD_CEP NOT LIKE '58%')
    OR  (DS_UF = 'PE' AND (CD_CEP NOT LIKE '50%' AND CD_CEP NOT LIKE '51%' AND CD_CEP NOT LIKE '52%' AND CD_CEP NOT LIKE '53%' AND CD_CEP NOT LIKE '54%' AND CD_CEP NOT LIKE '55%' AND CD_CEP NOT LIKE '56%'))
    OR  (DS_UF = 'PI' AND CD_CEP NOT LIKE '64%')
    OR  (DS_UF = 'PR' AND (CD_CEP NOT LIKE '80%' AND CD_CEP NOT LIKE '81%' AND CD_CEP NOT LIKE '82%' AND CD_CEP NOT LIKE '83%' AND CD_CEP NOT LIKE '84%' AND CD_CEP NOT LIKE '85%' AND CD_CEP NOT LIKE '86%' AND CD_CEP NOT LIKE '87%'))
    OR  (DS_UF = 'RJ' AND (CD_CEP NOT LIKE '20%' AND CD_CEP NOT LIKE '21%' AND CD_CEP NOT LIKE '22%' AND CD_CEP NOT LIKE '23%' AND CD_CEP NOT LIKE '24%' AND CD_CEP NOT LIKE '25%' AND CD_CEP NOT LIKE '26%' AND CD_CEP NOT LIKE '27%' AND CD_CEP NOT LIKE '28%'))
    OR  (DS_UF = 'RN' AND CD_CEP NOT LIKE '59%')
    OR  (DS_UF = 'RO' AND CD_CEP NOT LIKE '789%')
    OR  (DS_UF = 'RR' AND CD_CEP NOT LIKE '693%')
    OR  (DS_UF = 'RS' AND CD_CEP NOT LIKE '9%')
    OR  (DS_UF = 'SC' AND (CD_CEP NOT LIKE '88%' AND CD_CEP NOT LIKE '89%'))
    OR  (DS_UF = 'SE' AND CD_CEP NOT LIKE '49%')
    OR  (DS_UF = 'SP' AND (CD_CEP NOT LIKE '0%' AND CD_CEP NOT LIKE '1%'))
    OR  (DS_UF = 'TO' AND CD_CEP NOT LIKE '77%')); COMMIT;
 
DELETE FROM TMP_PROC_DBM_ENDR_COMP
 WHERE FG_VALD = 0; COMMIT;


--COMPANY

  DROP TABLE TAB_PROC_DBM_COMP_UNIF;
CREATE TABLE TAB_PROC_DBM_COMP_UNIF AS
SELECT A.NR_CPF
     , A.DS_NOME
	 , A.NR_IDAD
     , A.DT_NASC
     , A.DS_GENR
     , B.DS_MAIL
     , B.FG_INTR
     , B.FG_INTR_12M
     , B.FG_INTR_18M
     , B.FG_INTR_24M
     , C.NR_DDD_TELF
     , C.NR_TELF
     , D.NR_DDD_TELF AS NR_DDD_CELL
     , D.NR_TELF     AS NR_CELL
     , E.DS_UF
     , E.DS_CIDD
     , E.CD_CEP
     , E.DS_BAIR
     , E.DS_TP_LOGR
     , E.DS_LOGR
     , E.DS_NUMR
     , E.DS_COMP
     , E.DS_TP_LOGR || ' ' || DS_LOGR || ', ' || DS_NUMR || ' - ' || DS_COMP AS DS_LOGR_CMPL
  FROM TMP_PROC_DBM_NOME_COMP      A
  LEFT JOIN TMP_PROC_DBM_MAIL_COMP B
    ON A.NR_CNPJ = B.NR_CNPJ
  LEFT JOIN TMP_PROC_DBM_TELF_COMP C
    ON A.NR_CNPJ = C.NR_CNPJ
   AND C.DS_TP_TELF = 'FIXO'
  LEFT JOIN TMP_PROC_DBM_TELF_COMP D
    ON A.NR_CNPJ = D.NR_CNPJ
   AND D.DS_TP_TELF = 'CELULAR'
  LEFT JOIN TMP_PROC_DBM_ENDR_COMP E
    ON A.NR_CNPJ = E.NR_CNPJ