--CRIACAO DE TABELA DE COMPRA

CREATE TABLE TMP_ESTUDO_RANGER_COMPRADORES AS
SELECT  DISTINCT CAST(I.CPF AS NUMERIC)AS CPF
,DP.MODELO
,VR.DTPURCHASE
,ROW_NUMBER() OVER(PARTITION BY CAST(I.CPF AS NUMERIC) ORDER BY VR.DTPURCHASE DESC) NR_SEQC

  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP 
    ON VF.CDTMA = DP.CDTMA
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2019','DD/MM/YYYY') AND TO_DATE('31/12/2019','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0'
   AND DP.MODELO_BIA LIKE '%RANGER%' 


 DELETE FROM TMP_ESTUDO_RANGER_COMPRADORES 
 WHERE NR_SEQC <> 1; COMMIT; 

-- CRIACAO DE TABELA DE SUPORTE PARA SEPARAR CLIENTES NOVOS COM O PRIMEIRO CARRO DA TABELA DE COMPRA E  CLIENTES ANTIGOS(COM OUTROS CARROS )

CREATE TABLE TMP_ESTUDO_RANGER_COMPRA_FL  AS 
SELECT DISTINCT  CAST(I.CPF AS NUMERIC)AS CPF

  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP 
    ON VF.CDTMA = DP.CDTMA
    INNER JOIN TMP_ESTUDO_RANGER_COMPRADORES L
    ON I.CPF = L.CPF
    AND TO_DATE(VR.DTPURCHASE,'DD/MM/YY') < TO_DATE(L.DTPURCHASE,'DD/MM/YY')
 --WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2017','DD/MM/YYYY') AND TO_DATE('31/12/2019','DD/MM/YYYY')
   WHERE (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0'

-- CRIACAO DE TABELA FINAL 

CREATE TABLE TMP_ESTUDO_RANGER  AS 
SELECT CAST(I.CPF AS NUMERIC)AS CPF
,D.DS_NOME AS Nome 
,I.DTPURCHASE AS Data_Compra
,I.MODELO AS MODELO
,D.DS_MAIL AS Email
,D.NR_DDD_CELL||D.NR_CELL as Celular
,D.NR_TELF AS Telefone
,D.DS_UF AS Estado 
, CASE WHEN L.CPF IS NULL THEN '0'
       WHEN L.CPF IS NOT NULL THEN '1'
       END AS CLIENTE_ANTIGO

FROM TMP_ESTUDO_RANGER_COMPRADORES I
INNER JOIN TAB_PROC_DBM_CLIE_UNIF D
ON  I.CPF = D.NR_CPF
LEFT JOIN TMP_ESTUDO_RANGER_COMPRA_FL L
ON I.CPF = L.CPF 

--LIMPEZA ESTRUTURAS

DROP TABLE TMP_ESTUDO_RANGER_COMPRADORES; COMMIT; 
DROP TABLE TMP_ESTUDO_RANGER_COMPRA_FL; COMMIT; 
DROP TABLE TMP_ESTUDO_RANGER; COMMIT; 

SELECT * FROM TMP_ESTUDO_RANGER


CREATE TABLE AS TMP_REQUISICAO_GILLIARD
SELECT A.*,B.*
FROM TMP_ESTUDO_RANGER A 
LEFT JOIN vendas_ranger_antigo_atual B 
ON A.CPF = B.CPF

