
  DROP TABLE TMP_PROC_DBM_NOME; 
CREATE TABLE TMP_PROC_DBM_NOME AS
SELECT I.NMINDIVIDUAL          AS DS_NOME
     , CAST(I.CPF AS NUMERIC)  AS NR_CPF
     ,CASE  WHEN SUBSTR(B.DTBIRTHDATE,7,1) <= 1 AND SUBSTR(B.DTCREATE,7,2) < 22 THEN EXTRACT (YEAR FROM SYSDATE) - (20||SUBSTR(B.DTBIRTHDATE,7,2))
            WHEN SUBSTR(B.DTBIRTHDATE,7,1) <=1 AND SUBSTR(B.DTCREATE,7,2) BETWEEN 22 AND 99 THEN EXTRACT (YEAR FROM SYSDATE) - (19||SUBSTR(B.DTBIRTHDATE,7,2))
           WHEN B.DTBIRTHDATE IS NULL THEN 0
           WHEN SUBSTR(B.DTBIRTHDATE,7,1) > 1  THEN EXTRACT (YEAR FROM SYSDATE) - (19||SUBSTR(B.DTBIRTHDATE,7,2))
           END AS NR_IDADE
     , CASE WHEN OP.ID_INDV IS NULL THEN 0 ELSE 1 END AS FG_OPTO
     , ROW_NUMBER() OVER(PARTITION BY CAST(I.CPF AS NUMERIC) ORDER BY I.DTLASTUPDATE DESC) AS NR_SEQC
  FROM FORD.INDIVIDUAL        I 
 INNER JOIN TMP_PROC_DBM_PUBL D
    ON I.IDINDIVIDUAL = D.ID_INDV
  LEFT JOIN TMP_OPTO          OP
    ON I.IDINDIVIDUAL = OP.ID_INDV
  LEFT JOIN FORD.INDIVIDUALSTANDARDDEMOGRAPHICS B
    ON  I.IDINDIVIDUAL = B.IDINDIVIDUAL
 WHERE REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL;   
COMMIT;

DELETE FROM TMP_PROC_DBM_NOME
 WHERE NR_SEQC <> 1; COMMIT;


