SELECT SUBSTR(CAPP01_CREATE_S, 4,7) AS DS_ANOMES
     , CAPP01_CREATE_S              AS DT_CADR
     --, CASE WHEN B.CD_TMA IN ('2BC','4BC','3BB','4BB','6BC','7BC','6BB','7BB','RAN') THEN 1 ELSE 0 END AS FG_RANG
     , CASE WHEN CAPP03_VIN_C IS NULL THEN 0 ELSE 1 END AS FG_VIN_CADR
     ,B.DT_COMP 
     ,CASE WHEN SUBSTR(TO_DATE(SYSDATE, 'DD/MM/YY'),7,1) - SUBSTR(TO_DATE(B.DT_COMP, 'DD/MM/YY'),7,1) = 1  THEN '1ªRevisão'
          WHEN SUBSTR(TO_DATE(SYSDATE, 'DD/MM/YY'),7,1) - SUBSTR(TO_DATE(B.DT_COMP ,'DD/MM/YY'),7,1) = 2  THEN '2ªRevisão'
          WHEN SUBSTR(TO_DATE(SYSDATE ,'DD/MM/YY'),7,1) - SUBSTR(TO_DATE(B.DT_COMP ,'DD/MM/YY'),7,1) >= 3  THEN '3ªRevisão'
          ELSE 'Sem necessidade de Revisão' END REVISÃO 
FROM SERBINOC.BASE_DOWNLOAD_FORD_PASS A
LEFT JOIN TMP_PROC_DBM_VEIC B
ON A.CAPP03_VIN_C = CD_CHAS
WHERE B.CD_TMA IN ('2BC','4BC','3BB','4BB','6BC','7BC','6BB','7BB','RAN')

SELECT * FROM TMP_PROC_DBM_VEIC