DROP TABLE TMP_CLASSF_RANGER
CREATE TABLE TMP_CLASSF_RANGER AS
SELECT A.*
, B.DT_COMP AS DT_COMP_B
, B.ID_VEIC AS ID_VEIC_B
, B.CD_CHAS AS CD_CHAS_B
, B.CD_TMA AS CD_TMA_B
, B.CD_SEQC AS CD_SEQC_B
, B.DS_MODL_ESPC AS DS_MODL_ESPC_B
, B.DS_MODL AS DS_MODL_B
, B.DS_MODL_ANO AS DS_MODL_ANO_B
, B.DS_MODL_RESM AS DS_MODL_RESM_B
, B.ID_DEAL AS ID_DEAL_B
, A.DT_COMP - B.DT_COMP AS QT_DIAS
, D.CLASSIFICAÇÃO AS CLASSF_ANTIGO
, C.CLASSIFICAÇÃO AS CLASSF_ATUAL
FROM TMP_COMP_RANG A
INNER JOIN TMP_PROC_DBM_VEIC B
ON A.NR_CPF = B.NR_CPF
AND B.NR_SEQC = 2
AND B.CD_TMA IN ('2BC','4BC','3BB','4BB','6BC','7BC','6BB','7BB','RAN')
LEFT JOIN TMP_DEPARA_MODEL_RANGER C
ON A.CD_SEQC = C.SEQ
LEFT JOIN TMP_DEPARA_MODEL_RANGER D
ON B.CD_SEQC = D.SEQ