--Inserção Dados

INSERT INTO COMPRADORES_FACEBOOK
SELECT VR.IDVEHICLE
,VR.IDVEHICLEHOLDER
,MM.DSMAKER
,MM.DSMODEL
,MM.DSGENERICMODEL
,MM.DSORIGINALMODEL
,MM.DSCATEGORY
,MM.DSSEGMENT
,VF.CDTMA
,I.TPGENDER
,I.CPF
,I.NMINDIVIDUAL
,I.NMFIRST
,COM.CNPJ
,COM.NMCOMPANY
,EM.DSEMAIL
,P.IDPERSON
,P.DTCREATE
,VR.DTPURCHASE
,NULL AS TP_PESSOA
FROM FORD.VEHICLERELATIONSHIP VR,
FORD.VEHICLE V,
FORD.MAKERMODEL MM,
FORD.VEHICLEFACT VF,
FORD.INDIVIDUAL I,
FORD.PERSON P,
FORD.COMPANY COM,
(SELECT EM.*, 
RANK() OVER(PARTITION BY IDPERSON ORDER BY DTLASTUPDATE DESC, IDEMAIL DESC) RANK_EM 
FROM FORD.EMAIL EM 
WHERE FLUSEROW = 'S' AND CDNIXIETYPE IS NULL) EM 
WHERE VR.IDVEHICLE = V.IDVEHICLE
AND V.DSORIGINALMODEL = MM.DSORIGINALMODEL
AND V.IDVEHICLE = VF.IDVEHICLE
AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
AND VR.FLSTILLOWNED ='S' -- POSSUI O VEICULO
AND VR.IDVEHICLEHOLDER = P.IDPERSON
AND P.IDPERSON = I.IDINDIVIDUAL(+)
AND P.IDPERSON = COM.IDCOMPANY(+)
AND MONTHS_BETWEEN(SYSDATE,VR.DTPURCHASE) <= 6 --PERIODO DE 6 MESES
AND P.IDPERSON = EM.IDPERSON(+)
AND RANK_EM(+) = 1
AND EM.DSEMAIL IS NOT NULL -- TRAZER E-MAILS SEM SER NULOS
AND VF.CDTMA IN ('BDA','KHC','KFA','GDA','FHC','FFC','NFB','NFA','FAD','BFA','BFC','BHC','CFA',
                'CHC','EUA','BUA','FFA','FFB','EEF','2BC','4BC','3BB','4BB','6BC','7BC','6BB','7BB','NBJ');
COMMIT;

DELETE FROM COMPRADORES_FACEBOOK WHERE DSGENERICMODEL IN (
'COURIER'
,'F4000'
,'CARGO'
,'F350'
,'TRANSIT');COMMIT;

DELETE FROM COMPRADORES_FACEBOOK WHERE DSORIGINALMODEL IN
(
 'FORD/CARGO 2423 B'
,'FORD/CARGO 1419 S'
,'FORD/CARGO 1519 S'
,'FORD/CARGO 1723 BL'
,'FORD/CARGO 1933 BTL'
,'FORD/CARGO 2429 BL'
,'FORD/CARGO 2429 B'
,'FORD/CARGO 1723 B'
,'FORD/CARGO 3129 6X4'
,'FORD/CARGO 1729 B'
,'FORD/CARGO 1719 S'
,'FORD/CARGO 2423 BL'
,'FORD/CARGO 1729 BL'
);COMMIT;
 
  /*
  SELECT COUNT(*)
FROM FORD.VEHICLERELATIONSHIP VR,
FORD.VEHICLE V,
FORD.MAKERMODEL MM,
FORD.VEHICLEFACT VF,
FORD.INDIVIDUAL I,
FORD.PERSON P,
FORD.COMPANY COM,
(SELECT EM.*, 
RANK() OVER(PARTITION BY IDPERSON ORDER BY DTLASTUPDATE DESC, IDEMAIL DESC) RANK_EM 
FROM FORD.EMAIL EM 
WHERE FLUSEROW = 'S' AND CDNIXIETYPE IS NULL) EM 
WHERE VR.IDVEHICLE = V.IDVEHICLE
AND V.DSORIGINALMODEL = MM.DSORIGINALMODEL
AND V.IDVEHICLE = VF.IDVEHICLE
AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
AND VR.FLSTILLOWNED ='S' -- POSSUI O VEICULO
AND VR.IDVEHICLEHOLDER = P.IDPERSON
AND P.IDPERSON = I.IDINDIVIDUAL(+)
AND P.IDPERSON = COM.IDCOMPANY(+)
AND MONTHS_BETWEEN(SYSDATE,VR.DTPURCHASE) <= 6 --PERIODO DE 6 MESES
AND P.IDPERSON = EM.IDPERSON(+)
AND RANK_EM(+) = 1
AND EM.DSEMAIL IS NOT NULL -- TRAZER E-MAILS SEM SER NULOS
AND VF.CDTMA IN ('BDA','KHC','KFA','GDA','FHC','FFC','NFB','NFA','FAD','BFA','BFC','BHC','CFA',
                'CHC','EUA','BUA','FFA','FFB','EEF','2BC','4BC','3BB','4BB','6BC','7BC','6BB','7BB','NBJ');
                
  */
  DELETE FROM COMPRADORES_FACEBOOK WHERE CDTMA IN ('EAC','EAL','EB5','EAH','EBJ');COMMIT;
  
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'RANGER' WHERE CDTMA = '7BB' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'RANGER' WHERE CDTMA = '7BC' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'RANGER' WHERE CDTMA = '6BC' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'NEW FIESTA' WHERE CDTMA = 'FAD' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'RANGER' WHERE CDTMA = '6BB' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'FOCUS SEDAN' WHERE CDTMA = 'CFA' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'FOCUS HATCH' WHERE CDTMA = 'CHC' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'ECOSPORT' WHERE CDTMA = 'BUA' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'KA' WHERE CDTMA = 'KFA' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'NEW FIESTA' WHERE CDTMA = 'BFA' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'KA' WHERE CDTMA = 'KHC' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'NOVO EDGE' WHERE CDTMA = 'EMA' AND DSGENERICMODEL IS NULL;COMMIT;
  UPDATE COMPRADORES_FACEBOOK SET DSGENERICMODEL = 'NOVO FUSION' WHERE CDTMA = 'FFB' AND DSGENERICMODEL IS NULL;COMMIT;
  
    
UPDATE COMPRADORES_FACEBOOK AA SET AA.TP_PESSOA = 'FISICA'
WHERE EXISTS (SELECT 1 FROM FORD.INDIVIDUAL BB WHERE AA.IDVEHICLEHOLDER = BB.IDINDIVIDUAL);COMMIT;

UPDATE COMPRADORES_FACEBOOK AA SET AA.TP_PESSOA = 'JURIDICA'
WHERE EXISTS (SELECT 1 FROM FORD.COMPANY BB WHERE AA.IDVEHICLEHOLDER = BB.IDCOMPANY);COMMIT;


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--TABELAS NA QUERY

--TABELAS FORD

FORD.VEHICLERELATIONSHIP
FORD.VEHICLE
FORD.MAKERMODEL
FORD.VEHICLEFACT
FORD.INDIVIDUAL
FORD.PERSON
FORD.COMPANY
FORD.EMAIL

--TABELAS TRUNCADAS
COMPRADORES_FACEBOOK 


