
--CPF X CNPJ TABELA BASE
DROP TABLE TMP_PROC_TRAN_JUD_FIS;COMMIT;
CREATE TABLE TMP_PROC_TRAN_JUD_FIS AS 
       SELECT NR_CPF
       ,DT_COMP
       ,CD_CHAS
       ,DS_MODL_RESM
       ,DS_MODL_ESPC
       ,ID_DEAL
       ,NR_SEQC
       ,DS_MODL
       ,'FISICA' PESSOA 
FROM TAB_PROC_DBM_TRAN
UNION ALL
       SELECT NR_CNPJ
       ,DT_COMP
       ,CD_CHAS
       ,DS_MODL_RESM
       ,DS_MODL_ESPC
       ,ID_DEALER
       ,NR_SEQC
       ,DS_MODL
       ,'JURIDICA' PESSOA 
FROM TAB_PROC_DBM_TRAN_COMP  
;COMMIT;


--CPF X CNPJ COMPORTAMENTO TABELA BASE 
DROP TABLE TMP_PROC_COMP_JUD_FIS;COMMIT;
CREATE TABLE TMP_PROC_COMP_JUD_FIS AS 
        SELECT NR_CPF
       ,DS_MODL_ATUA
       ,DS_MODL_ANTE
       ,DT_COMP_ATUA
       ,DT_COMP_ANTE
       ,QT_CARR
       ,DT_PRIM_COMP
       ,DT_ULTM_COMP
       ,'FISICA' PESSOA 
FROM TAB_PROC_DBM_TRAN_CPTO
UNION ALL
       SELECT NR_CNPJ
       ,DS_MODL_ATUA
       ,DS_MODL_ANTE
       ,DT_COMP_ATUA
       ,DT_COMP_ANTE
       ,QT_CARR
       ,DT_PRIM_COMP
       ,DT_ULTM_COMP
       ,'JURIDICA' PESSOA 
FROM TAB_PROC_DBM_TRAN_CPTO_COMP  
;COMMIT;



--VENDAS CONVERTIDAS POR LEADS
DROP TABLE TMP_PROC_CONV_LEADS;COMMIT;
CREATE TABLE TMP_PROC_CONV_LEADS AS 
        SELECT DISTINCT A.NR_CPF
        ,A.CD_CHAS
        FROM TMP_PROC_TRAN_JUD_FIS           A
        INNER JOIN TAB_PROC_LEAD_HIST        B
          ON  A.NR_CPF = CAST (B.CPF AS NUMERIC)
        WHERE REPLACE(TRANSLATE(B.CPF, '1234567890', ' '),' ','') IS NULL   
          AND B.CPF <> '00000000000'
          AND A.DT_COMP BETWEEN TO_DATE(B.DATA_CRIACAO,'DD/MM/YY') AND TO_DATE(B.DATA_CRIACAO,'DD/MM/YY')+90
;COMMIT;


--CRIACAO TABELA FINAL 
DROP TABLE TAB_PROC_DASH_VENDAS;COMMIT;
CREATE TABLE TAB_PROC_DASH_VENDAS AS 
SELECT  CAST (I.NR_CPF AS NUMERIC) NR_CPF
        ,B.DS_MODL_ATUA 
        ,B.DS_MODL_ANTE
        ,B.DT_COMP_ATUA
        ,SUBSTR(B.DT_COMP_ATUA ,4,6) AS DT_MES_ANO_COMP
        ,B.DT_COMP_ANTE
        ,B.DT_PRIM_COMP
        ,B.DT_ULTM_COMP
        ,B.QT_CARR
        ,I.ID_DEAL
        ,A.NOME_DEALER
        ,ROUND((TO_DATE(B.DT_COMP_ATUA,'DD/MM/YY')- TO_DATE(B.DT_COMP_ANTE,'DD/MM/YY'))/30) AS TMP_RECOMPRA
        ,I.PESSOA
        ,CASE WHEN B.DT_COMP_ANTE IS NOT NULL THEN 'Y' 
              WHEN B.DT_COMP_ANTE IS NULL THEN     'N'
                END AS RECOMPRA
        ,CASE WHEN D.NR_CPF IS NOT NULL THEN       'Y' 
              WHEN D.NR_CPF IS NULL THEN           'N'
                END AS VENDA_POR_LEAD
        ,CASE WHEN LENGTH(I.ID_DEAL)= 4  THEN 'DEALER' 
              WHEN LENGTH(I.ID_DEAL)<> 4 THEN 'VENDA DIRETA' 
              WHEN I.ID_DEAL IS NULL THEN 'ID NULO' 
                END AS FLAG_DEALER
        ,CASE WHEN  B.DT_PRIM_COMP BETWEEN ADD_MONTHS(SYSDATE,-60) AND  SYSDATE 
              THEN '1 ' 
              ELSE '0' 
                END AS PRIMEIRA_COMPRA_60M
        ,CASE WHEN  B.DT_PRIM_COMP BETWEEN ADD_MONTHS(SYSDATE,-12) AND  SYSDATE
              THEN '1 '
              ELSE '0'  
                END AS PRIMEIRA_COMPRA_12M
        ,CASE WHEN  B.DT_PRIM_COMP BETWEEN ADD_MONTHS(SYSDATE,-1)  AND  SYSDATE
              THEN '1 ' 
              ELSE '0' 
                END AS PRIMEIRA_COMPRA_1M
        ,CASE WHEN UPPER(B.DS_MODL_ATUA) LIKE '%KA%' THEN 'KA' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%KA SEDAN%' THEN 'KA SEDAN' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%FIESTA%' THEN 'FIESTA' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%FIESTA SEDAN%' THEN 'FIESTA SEDAN'  
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%RANGER%' THEN 'RANGER' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%ECOSPORT%' THEN 'ECOSPORT' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%EDGE%' THEN 'EDGE' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%MUSTANG%' THEN 'MUSTANG' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%FUSION%' THEN 'FUSION' 
              WHEN UPPER(B.DS_MODL_ATUA) LIKE '%FOCUS%' THEN 'FOCUS' 
                END AS MODELO_ATUAL
        ,CASE WHEN UPPER(B.DS_MODL_ANTE) LIKE '%KA%'  THEN 'KA' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%KA SEDAN%' THEN 'KA SEDAN' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%FIESTA%' THEN 'FIESTA' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%FIESTA SEDAN%' THEN 'FIESTA SEDAN'  
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%RANGER%' THEN 'RANGER' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%ECOSPORT%' THEN 'ECOSPORT' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%EDGE%' THEN 'EDGE' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%MUSTANG%' THEN 'MUSTANG' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%FUSION%' THEN 'FUSION' 
              WHEN UPPER(B.DS_MODL_ANTE) LIKE '%FOCUS%' THEN 'FOCUS' 
                END AS MODELO_ANTERIOR
        FROM TMP_PROC_TRAN_JUD_FIS              I
        LEFT JOIN TMP_DEALERS                   A 
            ON I.ID_DEAL = A.ID_DEALER
        LEFT JOIN TMP_PROC_COMP_JUD_FIS         B
            ON I.NR_CPF = B.NR_CPF    
        LEFT JOIN TMP_PROC_CONV_LEADS           D
            ON I.NR_CPF = D.NR_CPF 
            AND I.CD_CHAS = D.CD_CHAS
;COMMIT;
