--NAMEPLATE

--EVOLUCAO DE VENDAS

SELECT DISTINCT CAST (I.NR_CPF AS NUMERIC)
,I.DT_COMP
,SUBSTR(I.DT_COMP ,4,6)
,I.DS_MODL_ESPC
,I.DS_MODL
FROM TMP_PROC_DBM_VEIC I
WHERE I.DS_MODL = 'RANGER'
AND I.DT_COMP BETWEEN TO_DATE('01/01/14','DD/MM/YY') AND TO_DATE('31/12/19','DD/MM/YY')
ORDER BY I.DT_COMP ASC

-- TOP DEALERS RANGER

SELECT DISTINCT CAST (I.NR_CPF AS NUMERIC)
,I.DT_COMP
,SUBSTR(I.DT_COMP ,4,6)
,I.DS_MODL_ESPC
,I.DS_MODL
,I.ID_DEALER
,A.NOME_DEALER
,UF
,REGIONAL
FROM TMP_PROC_DBM_VEIC I
LEFT JOIN TMP_DEALERS A 
ON I.ID_DEALER = A.ID_DEALER
WHERE I.DS_MODL = 'RANGER'
AND I.DT_COMP BETWEEN TO_DATE('01/01/14','DD/MM/YY') AND TO_DATE('31/12/19','DD/MM/YY')


--FIDELIDADE AO DEALER(REVENDAS)



CREATE TABLE TMP_VENDAS_ESTUDO_RANGER  AS 
SELECT  DISTINCT CAST (I.CPF AS NUMERIC) AS CPF
,I.DS_MODL_ESPC AS MODELO_RANGER
,I.DT_COMP AS DT_COMP_RANGER
,I.ID_DEALER AS ID_DEALER_RANGER
,I.NOME_DEALER
,A.DS_MODL_ESPC
,A.DT_COMP
,A.ID_DEALER
,ROW_NUMBER() OVER(PARTITION BY CAST(A.NR_CPF AS NUMERIC) ORDER BY A.DT_COMP ASC) NR_SEQC
,CASE WHEN I.ID_DEALER = A.ID_DEALER 
THEN '1'
ELSE '0'
END AS FLAG_DEALER_COMP
FROM TMP_VENDAS_RANGER I 
LEFT JOIN TMP_PROC_DBM_VEIC A 
ON I.CPF = CAST(A.NR_CPF AS NUMERIC)
AND  TO_DATE(A.DT_COMP,'DD/MM/YY')  < TO_DATE(I.DT_COMP,'DD/MM/YY')

 CREATE TABLE TMP_SUM_DEALER AS
SELECT B.ID_DEALER,
COUNT(B.FLAG_DEALER_COMP) AS CONTADOR
FROM TMP_VENDAS_ESTUDO_RANGER B
WHERE B.FLAG_DEALER_COMP = 1
GROUP BY B.ID_DEALER


CREATE TABLE TMP_SUM_DEALER_FINAL AS 
SELECT A.*,
B.NOME_DEALER
FROM TMP_SUM_DEALER A
LEFT JOIN TMP_DEALERS B 
ON A.ID_DEALER = B.ID_DEALER

-- FORD PASS 

--Quantidade de usuários (CPF) que fizeram download do FordPass - 485

SELECT COUNT  ( DISTINCT CAST (A.CPF AS NUMERIC) ) 
FROM SERBINOC.BASE_DOWNLOAD_FORD_PASS A 
INNER JOIN TMP_PROC_DBM_VEIC B
ON A.CPF = CAST(B.NR_CPF AS NUMERIC ) 
WHERE B.DS_MODL = 'RANGER'
AND B.DT_COMP BETWEEN TO_DATE('01/01/14','DD/MM/YY') AND TO_DATE('31/12/19','DD/MM/YY')
AND REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL 

--Quantidade de usuários (CPF) que fizeram download do FordPass e têm VIN preenchido - 359
SELECT COUNT  ( DISTINCT CAST (A.CPF AS NUMERIC) ) 
FROM SERBINOC.BASE_DOWNLOAD_FORD_PASS A 
INNER JOIN TMP_PROC_DBM_VEIC B
ON A.CPF = CAST(B.NR_CPF AS NUMERIC ) 
WHERE B.DS_MODL = 'RANGER'
AND B.DT_COMP BETWEEN TO_DATE('01/01/14','DD/MM/YY') AND TO_DATE('31/12/19','DD/MM/YY') 
AND REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL 


--Evolução de Novos Membros mês a mês 

SELECT DISTINCT CAST (A.CPF AS NUMERIC) 
,CAPP01_CREATE_S
FROM SERBINOC.BASE_DOWNLOAD_FORD_PASS A 
INNER JOIN TMP_PROC_DBM_VEIC B
ON A.CPF = CAST(B.NR_CPF AS NUMERIC ) 
WHERE B.DS_MODL = 'RANGER'
AND REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL 


--Evolução de Novos Membros VIN mês a mês 

SELECT DISTINCT CAST (A.CPF AS NUMERIC) 
,CAPP01_CREATE_S
FROM SERBINOC.BASE_DOWNLOAD_FORD_PASS A 
INNER JOIN TMP_PROC_DBM_VEIC B
ON A.CPF = CAST(B.NR_CPF AS NUMERIC ) 
WHERE B.DS_MODL = 'RANGER'
AND REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL 
AND CAPP03_VIN_C IS NOT NULL 
