CREATE TABLE TMP_ESTUDO_OWNERS_5Y  AS 

SELECT  CAST(A.NR_CPF AS NUMERIC)AS CPF
,A.QT_CARRO AS QUANTIDADE 
,A.NOVO AS MODELO_ATUAL 
,A.ANTIGO AS MODELO_ANTERIOR
,A.DT_ULTM_COMP AS DT_ULTIM_COMPRA
FROM TMP_PROC_DBM_VEIC_FINAL A
WHERE TO_DATE(A.DT_ULTM_COMP,'DD/MM/YY') >= TO_DATE('01/01/14','DD/MM/YY')
