DROP TABLE TMP_ESTUDO_MUSTANG_COMPRADORES

CREATE TABLE TMP_ESTUDO_MUSTANG_COMPRADORES AS
SELECT  DISTINCT CAST(I.CPF AS NUMERIC)AS CPF
,DP.MODELO_BIA
,ROW_NUMBER() OVER(PARTITION BY CAST(I.CPF AS NUMERIC) ORDER BY VR.DTPURCHASE DESC) NR_SEQC

  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP 
    ON VF.CDTMA = DP.CDTMA
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2000','DD/MM/YYYY') AND TO_DATE('31/12/2025','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0'
   AND DP.CDTMA IN  ('6BC','RAN','FFA','FFB','7BC','6BB','7BB','2BC','4BC','3BB','4BB','EUA','BUA','EEF','WUA9','EMA')

 DELETE FROM TMP_ESTUDO_MUSTANG_COMPRADORES 
 WHERE NR_SEQC <> 1; COMMIT;


DROP TABLE TMP_ESTUDO_MUSTANG;

CREATE TABLE TMP_ESTUDO_MUSTANG  AS 

SELECT CAST(I.CPF AS NUMERIC)AS CPF
,B.MOSAIC_DESCRIPTION AS Mosaico
,I.MODELO_BIA AS Modelo
,D.DS_NOME AS Nome 
,D.DS_MAIL AS Email
,D.NR_TELF AS Telefone
,D.DS_UF AS Estado -- SELECT COUNT (*)
FROM TMP_ESTUDO_MUSTANG_COMPRADORES I
INNER JOIN TMP_PROC_DBM_EXPE B
ON  I.CPF = CAST(B.CPF AS NUMERIC)
LEFT JOIN TAB_PROC_DBM_CLIE_UNIF D
ON  I.CPF = D.NR_CPF
WHERE B.GENDER ='M' 
 AND B.SCHOLARITY = 'SUPERIOR COMPLETO'
 AND B.MOSAIC_DESCRIPTION IN ('Elite Urbana Qualificada','Ricos e Influentes','Empresàrios Estabilizados','Pequenos Negociantes do Interior')
 AND 2019 - (19||SUBSTR(B.DATE_OF_BIRTH,7,2)) BETWEEN 36 AND 55


   