--CRIACAO DE TABELA DE COMPRA
DROP TABLE TMP_DSG_THINKING_COMPRA

CREATE TABLE TMP_DSG_THINKING_COMPRA AS
SELECT  DISTINCT CAST(I.CPF AS NUMERIC)AS CPF
,DP.MODELO_BIA
,VR.DTPURCHASE
,ROW_NUMBER() OVER(PARTITION BY CAST(I.CPF AS NUMERIC) ORDER BY VR.DTPURCHASE DESC) NR_SEQC

  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP 
    ON VF.CDTMA = DP.CDTMA
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2017','DD/MM/YYYY') AND TO_DATE('31/12/2019','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0'
   AND DP.CDTMA IN  ('EUA','BUA','GDA','BDA','KHC','KFA')

 DELETE FROM TMP_DSG_THINKING_COMPRA 
 WHERE NR_SEQC <> 1; COMMIT; 

-- CRIACAO DE TABELA DE SUPORTE PARA SEPARAR CLIENTES NOVOS COM O PRIMEIRO CARRO DA TABELA DE COMPRA E  CLIENTES ANTIGOS(COM OUTROS CARROS )
DROP TABLE TMP_DSG_THINKING_COMPRA_FL; 

CREATE TABLE TMP_DSG_THINKING_COMPRA_FL  AS 

SELECT DISTINCT  CAST(I.CPF AS NUMERIC)AS CPF

  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP 
    ON VF.CDTMA = DP.CDTMA
    INNER JOIN TMP_DSG_THINKING_COMPRA L
    ON I.CPF = L.CPF
    AND TO_DATE(VR.DTPURCHASE,'DD/MM/YY') < TO_DATE(L.DTPURCHASE,'DD/MM/YY')
 --WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2017','DD/MM/YYYY') AND TO_DATE('31/12/2019','DD/MM/YYYY')
   WHERE (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0'

-- CRIACAO DE TABELA FINAL 

DROP TABLE TMP_ESTUDO_DESIGN_THINKING;

CREATE TABLE TMP_ESTUDO_DESIGN_THINKING  AS 

SELECT CAST(I.CPF AS NUMERIC)AS CPF
,D.DS_NOME AS Nome 
,I.MODELO_BIA AS Modelo
,I.DTPURCHASE AS Data_Compra
,D.DS_MAIL AS Email
,D.FG_INTR_12M AS Interacao12
,D.FG_INTR_18M AS Interacao18
,D.FG_INTR_24M AS Interacao24
,D.NR_DDD_CELL||D.NR_CELL as Celular
,D.NR_TELF AS Telefone
,D.DS_UF AS Estado 
, CASE WHEN L.CPF IS NULL THEN '0'
       WHEN L.CPF IS NOT NULL THEN '1'
       END AS CLIENTE_ANTIGO
--,2019 - (19||SUBSTR(B.DATE_OF_BIRTH,7,2)) AS IDADE
, CASE WHEN E.CPF IS NULL THEN '0'
       WHEN E.CPF IS NOT NULL THEN '1'
       END AS FORD_PASS
FROM TMP_DSG_THINKING_COMPRA I
INNER JOIN TMP_PROC_DBM_EXPE B
ON  I.CPF = CAST(B.CPF AS NUMERIC)
INNER JOIN TAB_PROC_DBM_CLIE_UNIF D
ON  I.CPF = D.NR_CPF
LEFT JOIN TMP_FORD_PASS_TEMPORARIA E 
ON I.CPF = CAST(E.CPF AS NUMERIC)
LEFT JOIN TMP_DSG_THINKING_COMPRA_FL L
ON I.CPF = L.CPF 
WHERE D.DS_UF = 'SP' 
AND 2019 - (19||SUBSTR(B.DATE_OF_BIRTH,7,2)) > 30



--TABELA FORD PASS TEMPORARIA PARA DEIXAR CAMPO DE CPF DISTINCT 
CREATE TABLE TMP_FORD_PASS_TEMPORARIA AS 
SELECT  DISTINCT CAST(I.CPF AS NUMERIC)AS CPF
FROM STG_PROC_FORD_PASS_CADR


--LIMPEZA ESTRUTURAS
DROP TABLE TMP_FORD_PASS_TEMPORARIA;
DROP TABLE TMP_DSG_THINKING_COMPRA_FL; 
DROP TABLE TMP_DSG_THINKING_COMPRA;

