
CREATE TABLE TMP_MUSTANG AS
SELECT CAST(I.CPF AS NUMERIC)AS CPF
     , MIN(DTPURCHASE)       AS ANO --select COUNT(*) FROM  TMP_MUSTANG
  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP -- SELECT * FROM FORD.VEHICLERELATIONSHIP
    ON VF.CDTMA = DP.CDTMA
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2000','DD/MM/YYYY') AND TO_DATE('31/12/2025','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0'
   AND DP.CDTMA = 'NBJ' 
 GROUP BY CAST(I.CPF AS NUMERIC)
 
SELECT COUNT(*), QT FROM ( 
SELECT COUNT(*)QT, CAST(I.CPF AS NUMERIC) CPF
  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP -- SELECT * FROM FORD.VEHICLERELATIONSHIP
    ON VF.CDTMA = DP.CDTMA
 INNER JOIN TMP_MUSTANG MU
    ON CAST(I.CPF AS NUMERIC) = MU.CPF
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2000','DD/MM/YYYY') AND TO_DATE('31/12/2025','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0'
 GROUP BY CAST(I.CPF AS NUMERIC)) GROUP BY QT ORDER BY 2
 
 
 DROP TABLE TMP_MUSTANG_ANTERIOR;
CREATE TABLE TMP_MUSTANG_ANTERIOR AS
SELECT CAST(I.CPF AS NUMERIC)AS CPF
     , MM.DSORIGINALMODEL
     , DP.MODELO_BIA
     , VR.DTPURCHASE
     , ROW_NUMBER() OVER(PARTITION BY CAST(I.CPF AS NUMERIC) ORDER BY VR.DTPURCHASE DESC) NR_SEQC
  FROM FORD.INDIVIDUAL I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 INNER JOIN DIASW.DEPARA_DASH DP -- SELECT * FROM FORD.VEHICLERELATIONSHIP
    ON VF.CDTMA = DP.CDTMA
 INNER JOIN TMP_MUSTANG    MT
    ON CAST(I.CPF AS NUMERIC) = MT.CPF
   AND VR.DTPURCHASE < MT.ANO
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/01/2000','DD/MM/YYYY') AND TO_DATE('31/12/2025','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD'
   AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL
   AND NVL(I.CPF,'0')<>'0';
 
DELETE FROM TMP_MUSTANG_ANTERIOR 
 WHERE NR_SEQC <> 1; COMMIT;
 
 CREATE TABLE TMP_MUSTANG_CALC AS
 SELECT A.CPF
      , A.ANO AS DT_MUSTANG
      , B.DSORIGINALMODEL
      , B.MODELO_BIA
      , B.DTPURCHASE
      , CASE WHEN A.ANO - B.DTPURCHASE IS NULL THEN '0 - não possui carro anterior'
             WHEN A.ANO - B.DTPURCHASE <= 365 THEN '1 - comprou carro até 1 ano antes'
             WHEN A.ANO - B.DTPURCHASE BETWEEN 365 AND 730 THEN '2 - comprou carro até 2 anos antes'
             WHEN A.ANO - B.DTPURCHASE BETWEEN 730 AND 1095 THEN '3 - comprou carro até 3 anos antes'
             WHEN A.ANO - B.DTPURCHASE BETWEEN 1095 AND 1460 THEN '4 - comprou carro até 4 anos antes'
             WHEN A.ANO - B.DTPURCHASE > 1460 THEN '5 - comprou carro há mais de 4 anos antes'
         END AS INTERVALO_VOLTA
   FROM TMP_MUSTANG a
   LEFT JOIN TMP_MUSTANG_ANTERIOR B
     ON A.CPF = B.CPF
  
  
SELECT COUNT(*), MODELO_BIA, INTERVALO_VOLTA
  FROM TMP_MUSTANG_CALC
 WHERE MODELO_BIA IS NOT NULL
  GROUP BY MODELO_BIA, INTERVALO_VOLTA
  ORDER BY 1 DESC
  
SELECT COUNT(*), CASE WHEN 2019-SUBSTR(DATE_BIRTH,7,4) <=25 THEN 'ATÉ 25'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) BETWEEN 26 AND 35 THEN 'DE 26 E 35'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) BETWEEN 36 AND 55 THEN 'DE 36 E 55'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) BETWEEN 56 AND 65 THEN 'DE 56 E 65'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) > 65 THEN 'MAIS DE 65' 
                      ELSE 'N/I' END FX_ETARIA
                      , GENDER, SCHOLARITY, MOSAIC_DESCRIPTION
  FROM TMP_MUSTANG A
  INNER JOIN TMP_PROC_DBM_EXPE B
  ON A.CPF = CAST(B.CPF AS NUMERIC)
 GROUP BY CASE WHEN 2019-SUBSTR(DATE_BIRTH,7,4) <=25 THEN 'ATÉ 25'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) BETWEEN 26 AND 35 THEN 'DE 26 E 35'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) BETWEEN 36 AND 55 THEN 'DE 36 E 55'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) BETWEEN 56 AND 65 THEN 'DE 56 E 65'
                      WHEN 2019-SUBSTR(DATE_BIRTH,7,4) > 65 THEN 'MAIS DE 65' 
                      ELSE 'N/I' END
                      , GENDER, SCHOLARITY, MOSAIC_DESCRIPTION
 ORDER BY 1 DESC
 
