
--Carregando Leads do m�s anterior

    SELECT DISTINCT ORIGEM_LEAD, SUB_ORIGEM--max(TO_DATE(DATA_CRIACAO,'DD/MM/YY'))
    FROM RESPORT_CRUZ_LEAD_MENSAL;
    
     INSERT INTO CRUZ_LEADS_2018_UNIFICADA
    SELECT CPF
    ,SUB_ORIGEM AS ORIGEM
    ,TMA
    ,TO_DATE(DATA_CRIACAO,'DD/MM/YY') AS DATA_CRIACAO
    ,DD.MODELO_FE AS MODELO_INTERESSE
    ,'SALESFORCE' AS SISTEMA
    ,ROW_NUMBER () OVER (PARTITION BY CPF,DATA_CRIACAO ORDER BY CPF,DATA_CRIACAO) ROWNO
    ,LEADS_MENSAL_SEQ.NEXTVAL
    ,ID_PRINCIPAL
    ,TEMPO_ATENDIMENTO
    --SELECT *
    FROM RESPORT_CRUZ_LEAD_MENSAL LEAD
    LEFT JOIN DIASW.DEPARA_DASH DD
    ON LEAD.TMA = DD.CDTMA;
    
    COMMIT;
    
        
    --Acrescentando 0 � esquerda
    
    UPDATE CRUZ_LEADS_2018_UNIFICADA
    SET CPF = LPAD(CPF,11,'0')
    WHERE LENGTH(CPF) < 11;
    COMMIT;

--Cruzando vendas

    DROP TABLE CRUZ_LEADS_2018_VENDAS;
    
    CREATE TABLE CRUZ_LEADS_2018_VENDAS AS
    SELECT A.*
    ,ROW_NUMBER () OVER (PARTITION BY CPF, DATA_CRIACAO ORDER BY DIAS_ATE_COMPRA) ROWNO_CPF
    FROM 
        (
        SELECT LEADS.CPF
        ,LEADS.DATA_CRIACAO
        ,LEADS.ROWNO AS ROWNO_LEAD
        ,LEADS.ID_SEQUENCIAL
        ,LEADS.CODIGO_OPORTUNIDADE
        ,VR.DTPURCHASE
        ,TRUNC(TO_DATE(VR.DTPURCHASE,'DD/MM/YY')) - TRUNC(LEADS.DATA_CRIACAO) AS DIAS_ATE_COMPRA
        ,VR.IDVEHICLEHOLDER
        ,VR.IDVEHICLE
        ,VR.FLSTILLOWNED
        ,VF.DSVIN
        ,TMA.CDTMA
        ,TMA.MODELO_FE AS MODELO_COMPRA
        ,VF.IDDEALERDELIVER
        ,VR.IDDEALER
        ,TRUNC(MONTHS_BETWEEN (LAST_DAY(SYSDATE),(LAST_DAY(DTPURCHASE)))) AS TEMPO_OWNED
        --,ROW_NUMBER () OVER (PARTITION BY VR.IDVEHICLE ORDER BY LEADS.DATA_CRIACAO, LEADS.ROWNO) ROWNO
        ,ROW_NUMBER () OVER (PARTITION BY VR.IDVEHICLE ORDER BY TO_DATE(DATA_CRIACAO,'DD/MM/YY'),LEADS.ROWNO) ROWNO
        FROM 
            (
            SELECT DISTINCT CPF
            ,DATA_CRIACAO
            ,ROWNO
            ,ID_SEQUENCIAL
            ,CODIGO_OPORTUNIDADE
            FROM CRUZ_LEADS_2018_UNIFICADA LEADS
            WHERE CPF IS NOT NULL
            ) LEADS
        INNER JOIN FORD.INDIVIDUAL I
        ON LEADS.CPF = I.CPF
        INNER JOIN FORD.VEHICLERELATIONSHIP VR
        ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
        INNER JOIN FORD.VEHICLE V
        ON VR.IDVEHICLE = V.IDVEHICLE
        INNER JOIN FORD.VEHICLEFACT VF
        ON V.IDVEHICLE = VF.IDVEHICLE
        INNER JOIN DIASW.DEPARA_DASH TMA
        ON VF.CDTMA = TMA.CDTMA
        LEFT JOIN 
            (
            SELECT DISTINCT IDVEHICLE
            FROM CRUZ_LEADS_VENDAS_HISTORICA
            )VEN
        ON VR.IDVEHICLE = VEN.IDVEHICLE
        WHERE DTPURCHASE <= SYSDATE
        --AND MONTHS_BETWEEN (TRUNC(SYSDATE,'MM'),TRUNC(LEADS.DATA_CRIACAO,'MM')) <= 3
        AND TO_DATE(VR.DTPURCHASE,'DD/MM/YY') >= TO_DATE(LEADS.DATA_CRIACAO,'DD/MM/YY')
        AND MONTHS_BETWEEN (TO_DATE(VR.DTPURCHASE,'DD/MM/YY'),TO_DATE(LEADS.DATA_CRIACAO,'DD/MM/YY')) <= 3 --Apenas 3 meses de matura��o
        AND TO_DATE(LEADS.DATA_CRIACAO) >= TRUNC(ADD_MONTHS(SYSDATE,-4),'MM') --Apenas meses ainda n�o maturados
        AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
        AND FLFIRSTOWNER = 'S'
        AND VEN.IDVEHICLE IS NULL
        ) A
    WHERE ROWNO = 1;
    
       
--Gravando na tabela hist�rica

    INSERT INTO CRUZ_LEADS_VENDAS_HISTORICA
    SELECT CPF
    ,DATA_CRIACAO
    ,ROWNO_LEAD
    ,DTPURCHASE
    ,DIAS_ATE_COMPRA
    ,IDVEHICLEHOLDER
    ,IDVEHICLE
    ,FLSTILLOWNED
    ,DSVIN
    ,CDTMA
    ,MODELO_COMPRA
    ,IDDEALERDELIVER
    ,IDDEALER
    ,TEMPO_OWNED
    ,ROWNO
    ,ROWNO_CPF
    ,ID_SEQUENCIAL
    ,CODIGO_OPORTUNIDADE
    FROM CRUZ_LEADS_2018_VENDAS;
    
    COMMIT;
    
    SELECT *
    --SELECT COUNT(1),COUNT(DISTINCT IDVEHICLE)
    FROM CRUZ_LEADS_VENDAS_HISTORICA;
    
    SELECT *
    FROM CRUZ_LEADS_2018_VENDAS;
    
    SELECT IDVEHICLE
    FROM CRUZ_LEADS_VENDAS_HISTORICA
    GROUP BY IDVEHICLE
    HAVING COUNT (1) > 1;
    
    SELECT *
    FROM CRUZ_LEADS_VENDAS_HISTORICA
    WHERE IDVEHICLE = 51792333;
    

--Gerando a base final
    
    DROP TABLE CRUZ_LEADS_2018_FINAL; -- SELECT SUM(QTD_LEADS), SUM(QTD_VENDAS) FROM CRUZ_LEADS_2018_FINAL -- 1.025.634    	24.017 
    
    CREATE TABLE CRUZ_LEADS_2018_FINAL AS
    SELECT TO_CHAR(LEAD.DATA_CRIACAO,'DD/MM/YYYY') AS DATA_CRIACAO
    ,COUNT (1) AS QTD_LEADS
    ,SUM(NVL(VEN.QTD_VENDAS,0)) AS QTD_VENDAS
    ,NVL(DP_ORG.ORIGEM_PARA,'Origem N�o Encontrada') AS ORIGEM
    ,LEAD.TEMPO_ATENDIMENTO
    ,CODIGO_CONCESSIONARIA
    FROM CRUZ_LEADS_2018_UNIFICADA LEAD
    LEFT JOIN 
        (
        SELECT ID_SEQUENCIAL, COUNT(IDVEHICLE) AS QTD_VENDAS
        FROM CRUZ_LEADS_VENDAS_HISTORICA
        GROUP BY ID_SEQUENCIAL
        ) VEN
    ON LEAD.ID_SEQUENCIAL = VEN.ID_SEQUENCIAL
    LEFT JOIN DEPARA_ORIGEM_LEADS_FMC DP_ORG
    ON LEAD.ORIGEM = DP_ORG.ORIGEM_DE
    LEFT JOIN RESPORT_CRUZ_LEAD_MENSAL OPT
    ON LEAD.codigo_oportunidade = OPT.id_principal
    GROUP BY TO_CHAR(LEAD.DATA_CRIACAO,'DD/MM/YYYY')
    ,NVL(DP_ORG.ORIGEM_PARA,'Origem N�o Encontrada')
    ,LEAD.TEMPO_ATENDIMENTO
    ,CODIGO_CONCESSIONARIA;
  
  
  
--Extra��o da contagem

    SELECT *
    FROM CRUZ_LEADS_2018_FINAL
    WHERE SUBSTR(DATA_CRIACAO,7,4)='2019';
    
--Vis�o de vendas por origem do Lead

-- SELECT SUM(QTD_LEAD), SUM(QTD_VENDAS) FROM ( -- SELECT * FROM CRUZ_LEADS_2018_UNIFICADA
   
    SELECT INITCAP(NVL(NVL(VENDA.MODELO_COMPRA,LEAD.MODELO_INTERESSE),'N�o Dispon�vel')) as NAMEPLATE
    ,NVL(DP_ORG.ORIGEM_PARA,'Origem N�o Encontrada') AS ORIGEM
    ,LEAD.DATA_CRIACAO
    ,COUNT(DISTINCT LEAD.ID_SEQUENCIAL) AS QTD_LEAD
    ,NVL(SUM(VENDA.QTD_VENDAS),0) AS QTD_VENDAS
    ,OPT.CODIGO_CONCESSIONARIA
    FROM CRUZ_LEADS_2018_UNIFICADA LEAD
    LEFT JOIN 
        (
        SELECT ID_SEQUENCIAL,MODELO_COMPRA,COUNT(DISTINCT IDVEHICLE) AS QTD_VENDAS
        FROM CRUZ_LEADS_VENDAS_HISTORICA
        --WHERE MODELO_COMPRA = 'EcoSport'
        GROUP BY ID_SEQUENCIAL,MODELO_COMPRA
        ) VENDA
    ON LEAD.ID_SEQUENCIAL = VENDA.ID_SEQUENCIAL
    LEFT JOIN DEPARA_ORIGEM_LEADS_FMC DP_ORG
    ON LEAD.ORIGEM = DP_ORG.ORIGEM_DE
    LEFT JOIN RESPORT_CRUZ_LEAD_MENSAL OPT
    ON LEAD.codigo_oportunidade = OPT.id_principal
    WHERE SUBSTR(LEAD.DATA_CRIACAO,7,2)='19'
    ON INITCAP(NVL(NVL(VENDA.MODELO_COMPRA,LEAD.MODELO_INTERESSE),'N�o Dispon�vel')) = 'RANGER'
    GROUP BY INITCAP(NVL(NVL(VENDA.MODELO_COMPRA,LEAD.MODELO_INTERESSE),'N�o Dispon�vel'))
    ,NVL(DP_ORG.ORIGEM_PARA,'Origem N�o Encontrada')
    ,LEAD.DATA_CRIACAO
    ,VENDA.QTD_VENDAS
    ,OPT.CODIGO_CONCESSIONARIA --)
   --1025706	24017
    