-----CUSTOMER------


--REGISTER

SELECT  A.ID_VALUE AS CPF
       ,B.INDIVIDUAL_FIRST_NAME  AS NMFIRST
       ,B.INDIVIDUAL_LAST_NAME AS NMLAST
       ,B.INDIVIDUAL_BIRTH_DATE AS DTBIRTHDATE
       ,B.INDIVIDUAL_GENDER AS TPGENDER
       ,B.LAST_UPDATE_DATE AS DTLASTUPDATE
       ,B.CONSUMER_ADDRESS_LINE_1 AS DSADDRESS
       ,B.CONSUMER_ADDRESS_LINE_2 AS NBNUMBER
       ,B.CONSUMER_ADDRESS_LINE_3 AS DSCOMPLEMENT
       ,B.CONSUMER_ZIP AS NBPOSTALCODE
       ,B.CITY_OR_SECONDARY_COUNTRY_DIV AS DSCITY
       ,B.STATE_OR_PRIMARY_CNTRY_DIV_CD AS CDSTATE
       ,B.LAST_UPDATE_DATE AS DTLASTUPDATE

FROM CONSUMER_IDENTIFIER_SA A
INNER JOIN CONSUMER_CURRENT_SA B 
 ON A.CONSUMER_ID = B.CONSUMER_ID
WHERE A.COUNTRY_CODE = 'BRA'


--EMAIL

SELECT  A.ID_VALUE AS CPF
       ,B.EMAIL_ADDRESS AS DSMAIL
       ,B.LAST_UPDATE_TIME AS DTLASTUPDATE
       ,B.EMAIL_SOURCE_CODE
FROM CONSUMER_IDENTIFIER_SA A
INNER JOIN CONSUMER_EMAIL_SA B 
 ON A.CONSUMER_ID = B.CONSUMER_ID
WHERE A.COUNTRY_CODE = 'BRA'



--PHONE

SELECT  A.ID_VALUE AS CPF
       ,B.PHONE_NUMBER AS NBTELEPHONE
       ,B.PHONE_NUMBER_TYPE_DESC AS NBAREACODE
       ,B.LAST_UPDATE_DATE AS DTLASTUPDATE
       ,B.PHONE_NUMBER_SOURCE AS NBPHONESOURCE

FROM CONSUMER_IDENTIFIER_SA A
INNER JOIN CONSUMER_PHONE_NUMBERS_SA B 
 ON A.CONSUMER_ID = B.CONSUMER_ID
WHERE A.COUNTRY_CODE = 'BRA'


-----COMPANY------


--REGISTER

SELECT  A.ID_VALUE AS CPF
       ,B.INDIVIDUAL_FIRST_NAME  AS NMFIRST
       ,B.INDIVIDUAL_LAST_NAME AS NMLAST
       ,B.INDIVIDUAL_BIRTH_DATE AS DTBIRTHDATE
       ,B.INDIVIDUAL_GENDER AS TPGENDER
       ,B.LAST_UPDATE_DATE AS DTLASTUPDATE
       ,B.CONSUMER_ADDRESS_LINE_1 AS DSADDRESS
       ,B.CONSUMER_ADDRESS_LINE_2 AS NBNUMBER
       ,B.CONSUMER_ADDRESS_LINE_3 AS DSCOMPLEMENT
       ,B.CONSUMER_ZIP AS NBPOSTALCODE
       ,B.CITY_OR_SECONDARY_COUNTRY_DIV AS DSCITY
       ,B.STATE_OR_PRIMARY_CNTRY_DIV_CD AS CDSTATE
       ,B.LAST_UPDATE_DATE AS DTLASTUPDATE

FROM CONSUMER_IDENTIFIER_SA A
INNER JOIN CONSUMER_CURRENT_SA B 
 ON A.CONSUMER_ID = B.CONSUMER_ID
WHERE A.COUNTRY_CODE = 'BRA'
--PARAMETROS PARA FILTRAR DADOS DE COMPANY - FLAG CPFORCNPJ

--EMAIL

SELECT  A.ID_VALUE AS CPF
       ,B.EMAIL_ADDRESS AS DSMAIL
       ,B.LAST_UPDATE_TIME AS DTLASTUPDATE
       ,B.EMAIL_SOURCE_CODE

FROM CONSUMER_IDENTIFIER_SA A
INNER JOIN CONSUMER_EMAIL_SA B 
 ON A.CONSUMER_ID = B.CONSUMER_ID
WHERE A.COUNTRY_CODE = 'BRA'
--PARAMETROS PARA FILTRAR DADOS DE COMPANY - FLAG CPFORCNPJ


--PHONE

SELECT  A.ID_VALUE AS CPF
       ,B.PHONE_NUMBER AS NBTELEPHONE
       ,B.PHONE_NUMBER_TYPE_DESC AS NBAREACODE
       ,B.LAST_UPDATE_DATE AS DTLASTUPDATE
       ,B.PHONE_NUMBER_SOURCE

FROM CONSUMER_IDENTIFIER_SA A
INNER JOIN CONSUMER_PHONE_NUMBERS_SA B 
 ON A.CONSUMER_ID = B.CONSUMER_ID
WHERE A.COUNTRY_CODE = 'BRA'
--PARAMETROS PARA FILTRAR DADOS DE COMPANY - FLAG CPFORCNPJ



-----TRANSACTION------

--CUSTOMER

SELECT  C.ID_VALUE AS CPF
       ,A.RETAIL_SALE_DATE AS DTPURCHASE
       ,A.VIN_CODE  AS DSVIN
       ,A.TMA_CODE AS CDTMA
       ,A.VERSION_SEQUENCE AS CDSEQ
       ,A.VEHICLE_LINE_DESC AS DSORIGINALMODEL
       ,A.LOCAL_MODEL_NAME AS DSMODEL
       ,A.VEHICLE_MODEL_YEAR AS DSMODELYEAR
       ,A.VEHICLE_COLOR AS DSCOLOR
       ,A.ENGINE_TYPE_DESC AS TPMOTOR
       ,A.RETAIL_SALE_DEALER AS NMDEALERCODE
FROM VEHICLE_MASTER_SA A
INNER JOIN VEHICLE_OWNERSHIP_CYCLE_FACT B 
 ON A.VIN_CODE = B.VIN_ID
INNER JOIN CONSUMER_IDENTIFIER_SA C 
 ON B.CONSUMER_ID = C.CONSUMER_ID
WHERE C.COUNTRY_CODE = 'BRA'
AND A.ORDERING_DEALER_COUNTRY_CODE = 'BRA'
AND EXTRACT(YEAR FROM A.RETAIL_SALE_DATE) >= 2000
AND A.VEHICLE_MAKE_DESC = 'FORD'
AND A.VEHICLE_TYPE_DESC = 'CAR'

--COMPANY

SELECT  C.ID_VALUE AS CPF
       ,A.RETAIL_SALE_DATE AS DTPURCHASE
       ,A.VIN_CODE  AS DSVIN
       ,A.TMA_CODE AS CDTMA
       ,A.VERSION_SEQUENCE AS CDSEQ
       ,A.VEHICLE_LINE_DESC AS DSORIGINALMODEL
       ,A.LOCAL_MODEL_NAME AS DSMODEL
       ,A.VEHICLE_MODEL_YEAR AS DSMODELYEAR
       ,A.VEHICLE_COLOR AS DSCOLOR
       ,A.ENGINE_TYPE_DESC AS TPMOTOR
       ,A.RETAIL_SALE_DEALER AS NMDEALERCODE
FROM VEHICLE_MASTER_SA A
INNER JOIN VEHICLE_OWNERSHIP_CYCLE_FACT B 
 ON A.VIN_CODE = B.VIN_ID
INNER JOIN CONSUMER_IDENTIFIER_SA C 
 ON B.CONSUMER_ID = C.CONSUMER_ID
WHERE C.COUNTRY_CODE = 'BRA'
AND A.ORDERING_DEALER_COUNTRY_CODE = 'BRA'
AND EXTRACT(YEAR FROM A.RETAIL_SALE_DATE) >= 2000
AND A.VEHICLE_MAKE_DESC = 'FORD'
AND A.VEHICLE_TYPE_DESC = 'CAR'
--PARAMETROS PARA FILTRAR DADOS DE COMPANY - FLAG CPFORCNPJ
