--CRIACAO ESTRUTURA DE FILTRAGEM DE USUARIOS PRESENTES NA BASE (BASE FORD)

CREATE TABLE TMP_CREDIT_ANALYSYS_PRESENT AS
  SELECT CAST (I.CPF AS NUMERIC) CPF
      ,I.SEXO
      ,I.IDADE
      ,I.UF_RES
      ,I.NOME_CIDADE
      ,I.BAIRRO_RES
      ,I.NOME_MODELO
      ,I.CD_CHASSI
      ,CONCAT(A.NR_DDD_CELL, A.NR_CELL) AS CELULAR
      ,A.DS_MAIL
      ,B.DT_COMP
      ,B.DS_MODL_ESPC AS MODELO_ESPECIFICACAO
      ,CASE WHEN A.NR_CPF IS NOT NULL 
            AND TO_DATE(B.DT_COMP,'DD/MM/YY') >= TO_DATE ('01/01/15','DD/MM/YY')
            AND B.DS_MODL_RESM = 'KA HATCH'
            AND (I.UF_RES = 'RS' OR I.UF_RES = 'BA')
            AND A.NR_CELL IS NOT NULL
            AND A.DS_MAIL IS NOT NULL 
            THEN 'Y'
       END AS FLAG_PRESENCA_BASE
      FROM TMP_FORD_CREDIT             I 
      LEFT JOIN TAB_PROC_DBM_CLIE_UNIF A
        ON CAST (I.CPF AS NUMERIC) = A.NR_CPF 
      LEFT JOIN TAB_PROC_DBM_TRAN      B
        ON I.CD_CHASSI = B.CD_CHAS



--CRIACAO ESTRUTURA DE FILTRAGEM DE USUARIOS NÃO PRESENTES NA BASE (BASE BRADESCO)

CREATE TABLE TMP_CREDIT_ANALYSYS_N_PRESENT AS
  SELECT CAST (I.CPF AS NUMERIC) CPF
      ,I.SEXO
      ,I.IDADE
      ,I.UF_RES
      ,I.NOME_CIDADE
      ,I.BAIRRO_RES
      ,I.NOME_MODELO
      ,I.CD_CHASSI
      ,CONCAT(A.NR_DDD_CELL, A.NR_CELL) AS CELULAR
      ,A.DS_MAIL
      ,B.DT_COMP
      ,B.DS_MODL_ESPC AS MODELO_ESPECIFICACAO
      ,CASE WHEN A.NR_CPF IS NOT NULL 
            AND TO_DATE(B.DT_COMP,'DD/MM/YY') >= TO_DATE ('01/01/15','DD/MM/YY')
            AND B.DS_MODL_RESM = 'KA HATCH'
            AND (I.UF_RES = 'RS' OR I.UF_RES = 'BA')
            AND A.NR_CELL IS NOT NULL
            AND A.DS_MAIL IS NOT NULL 
            THEN ''
            ELSE 'N'
       END AS FLAG_PRESENCA_BASE
      FROM TMP_FORD_CREDIT             I 
      LEFT JOIN TAB_PROC_DBM_CLIE_UNIF A
        ON CAST (I.CPF AS NUMERIC) = A.NR_CPF 
      LEFT JOIN TAB_PROC_DBM_TRAN      B
        ON I.CD_CHASSI = B.CD_CHAS

