  --Primeira Base
  
  DROP TABLE TMP_B1; COMMIT;
CREATE TABLE TMP_B1 AS
SELECT to_date(substr(MOMENTO_COMPRA,4,2)||'-'||substr(MOMENTO_COMPRA,1,2)||'-'||substr(MOMENTO_COMPRA,7,4),'DD-MM-YYYY') AS MOMENTO_COMPRA
     , DSVIN
     , MODELO
     , DSORIGINALMODEL
     , EMAIL
     , NOME
     
  FROM VW_ETL_AUTOS_FINAL  
 WHERE to_date(substr(MOMENTO_COMPRA,4,2)||'-'||substr(MOMENTO_COMPRA,1,2)||'-'||substr(MOMENTO_COMPRA,7,4),'DD-MM-YYYY') BETWEEN '01/08/2019 ' AND '31/01/2020'
   AND MODELO NOT IN ('Edge', 'Mustang'); COMMIT;
 
   DROP TABLE TMP_B11; COMMIT;
 CREATE TABLE TMP_B11 AS   
SELECT A.*
     , I.IDINDIVIDUAL
     , cast(I.CPF as numeric) CPF
     , ROW_NUMBER() OVER(PARTITION BY A.DSVIN ORDER BY VR.DTPURCHASE) NR_sEQC
  FROM FORD.INDIVIDUAL I 
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER 
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE 
 INNER JOIN TMP_B1  A
    ON VF.DSVIN = A.DSVIN;
 
 DELETE FROM TMP_B11
  WHERE NR_SEQC <> 1; COMMIT;
  
SELECT A.CPF
     , A.MOMENTO_COMPRA
     , A.MODELO
     , A.DSORIGINALMODEL
     , A.NOME
     , C.NR_DDD_TELF|| C.NR_TELF AS CELULAR
  FROM TMP_B11 A
  LEFT JOIN BENTOD.TAB_PROC_DBM_CLIE_UNIF C
    ON A.CPF = C.NR_CPF
   ORDER BY CASE WHEN C.NR_TELF IS NULL THEN 1 ELSE 0 END
        , MOMENTO_COMPRA
   

--Segunda base


SELECT CAST(A.CPF AS NUMERIC)
,C.DS_NOME
,C.NR_CELL
,MODELO_INTERESSE
,A.DATA_CRIACAO
FROM TAB_PROC_LEAD_HIST           A
LEFT JOIN TMP_PROC_DBM_VEIC_FINAL B
ON CAST (A.CPF AS NUMERIC) = B.NR_CPF
LEFT JOIN TAB_PROC_DBM_CLIE_UNIF  C 
ON CAST (A.CPF AS NUMERIC) = C.NR_CPF
WHERE A.MODELO_INTERESSE NOT IN ('Edge', 'Mustang')
AND REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL   
AND A.CPF <> '00000000000'
AND TO_DATE(A.DATA_CRIACAO,'DD/MM/YY') > TO_DATE('01/08/19','DD/MM/YY')
AND( TO_DATE(B.DT_ULTM_COMP,'DD/MM/YY')< TO_DATE(A.DATA_CRIACAO,'DD/MM/YY')  OR B.DT_ULTM_COMP IS NULL );

