-- CLIENTES PERIODO DE REVISAO



--SEGREGANDO PUBLICO SEM REVISAO 2020
DROP TABLE TMP_SEM_REVISAO_2020
CREATE TABLE TMP_SEM_REVISAO_2020 AS
SELECT DISTINCT DSVIN
FROM FORD.REVISION
WHERE DTREVISION < TO_DATE('01/01/2020','DD/MM/YYYY')

-- Email Marketing
SELECT DISTINCT
A.NR_CPF
,A.DS_MAIL
,B.DT_COMP
FROM TAB_PROC_DBM_CLIE_UNIF A
LEFT JOIN TAB_PROC_DBM_TRAN B
ON A.NR_CPF = B.NR_CPF
AND A.FG_INTR_12M = '1'
INNER JOIN TMP_SEM_REVISAO_2020 C
ON B.CD_CHAS = C.DSVIN
WHERE B.DT_COMP BETWEEN TO_DATE('01/03/2019','DD/MM/YYYY') AND TO_DATE('31/05/2019','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2018','DD/MM/YYYY') AND TO_DATE('31/05/2018','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2017','DD/MM/YYYY') AND TO_DATE('31/05/2017','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2016','DD/MM/YYYY') AND TO_DATE('31/05/2016','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2015','DD/MM/YYYY') AND TO_DATE('31/05/2015','DD/MM/YYYY')

--PUSH + InAPP
SELECT DISTINCT
A.CAPP01_USER_D_A AS USER_FORD_PASS
,A.NATIONALID
,A.CAPP01_EMAIL_ADDR_X AS EMAIL
,A.CAPP03_VIN_C AS CHASSI
,C.DT_COMP
FROM STG_PROC_FORD_PASS_CADR A
INNER JOIN TMP_SEM_REVISAO_2020 B
ON A.CAPP03_VIN_C = B.DSVIN
LEFT JOIN TAB_PROC_DBM_TRAN C
ON A.CAPP03_VIN_C = C.CD_CHAS
WHERE C.DT_COMP BETWEEN TO_DATE('01/03/2019','DD/MM/YYYY') AND TO_DATE('31/05/2019','DD/MM/YYYY')
OR C.DT_COMP BETWEEN TO_DATE  ('01/03/2018','DD/MM/YYYY') AND TO_DATE('31/05/2018','DD/MM/YYYY')
OR C.DT_COMP BETWEEN TO_DATE  ('01/03/2017','DD/MM/YYYY') AND TO_DATE('31/05/2017','DD/MM/YYYY')
OR C.DT_COMP BETWEEN TO_DATE  ('01/03/2016','DD/MM/YYYY') AND TO_DATE('31/05/2016','DD/MM/YYYY')
OR C.DT_COMP BETWEEN TO_DATE  ('01/03/2015','DD/MM/YYYY') AND TO_DATE('31/05/2015','DD/MM/YYYY')

-- SMS 
SELECT DISTINCT
A.NR_CPF
,CONCAT(A.NR_DDD_CELL, A.NR_CELL) AS CELULAR
,B.DT_COMP
FROM TAB_PROC_DBM_CLIE_UNIF A
LEFT JOIN TAB_PROC_DBM_TRAN B
ON A.NR_CPF = B.NR_CPF
AND A.NR_CELL IS NOT NULL
AND A.DS_MAIL IS NULL
INNER JOIN TMP_SEM_REVISAO_2020 C
ON B.CD_CHAS = C.DSVIN
WHERE B.DT_COMP BETWEEN TO_DATE('01/03/2019','DD/MM/YYYY') AND TO_DATE('31/05/2019','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2018','DD/MM/YYYY') AND TO_DATE('31/05/2018','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2017','DD/MM/YYYY') AND TO_DATE('31/05/2017','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2016','DD/MM/YYYY') AND TO_DATE('31/05/2016','DD/MM/YYYY')
OR B.DT_COMP BETWEEN TO_DATE  ('01/03/2015','DD/MM/YYYY') AND TO_DATE('31/05/2015','DD/MM/YYYY')



--COMPRAS SEM SAIR DE CASA


--EMAIL MARKETING
SELECT DISTINCT
A.NR_CPF
,A.DS_MAIL
,B.DT_COMP
,
FROM TAB_PROC_DBM_CLIE_UNIF A
LEFT JOIN TAB_PROC_DBM_TRAN B
ON A.NR_CPF = B.NR_CPF
WHERE B.DT_COMP > TO_DATE ('01/01/2015','DD/MM/YYYY')
AND A.FG_INTR_12M = '1'
AND A.NR_CELL IS NULL
AND A.DS_MAIL IS NOT NULL


--PUSH + InAPP
SELECT DISTINCT
A.CAPP01_USER_D_A AS USER_FORD_PASS
,A.NATIONALID
,A.CAPP01_EMAIL_ADDR_X AS EMAIL
,A.CAPP03_VIN_C AS CHASSI
,C.DT_COMP
FROM STG_PROC_FORD_PASS_CADR A

--SMS

SELECT DISTINCT
A.NR_CPF
,CONCAT(A.NR_DDD_CELL, A.NR_CELL) AS CELULAR
,B.DT_COMP
FROM TAB_PROC_DBM_CLIE_UNIF A
LEFT JOIN TAB_PROC_DBM_TRAN B
ON A.NR_CPF = B.NR_CPF
WHERE B.DT_COMP > TO_DATE ('01/01/2015','DD/MM/YYYY')
AND A.NR_CELL IS NOT NULL
AND A.DS_MAIL  NULL
