
-- REMOÇÃO DE TABELA PRINCIPAL 

DROP TABLE TMP_PROC_FORD_PASS_TRAT;

-- CRIAÇAO TABELA PRINCIPAL

CREATE TABLE TMP_PROC_FORD_PASS_TRAT (
USERID VARCHAR(150),
FIRST_ACCESS DATE,
YM_FIRSTACESS VARCHAR(150),
LASTACESS DATE,
YM_LASTACESS VARCHAR(150),
STATUS_USER VARCHAR(150),
USERTYPE VARCHAR(150),
RECENCY VARCHAR(150),
NAMEPLATE VARCHAR(150),
CARS_BY_USER VARCHAR(150),
MAINTANANCE VARCHAR(50),
FIDELITY VARCHAR(150),
CPF VARCHAR2(150)
) ;

-- CRIACAO TABELA TEMPORARIA TEMPO DE CASA(CONTAGEM DE FIDELIDADE)

CREATE TABLE TMP_TEMPO_CASA_FORD_PASS AS
SELECT CAST(I.CPF AS NUMERIC)  CPF
, MIN( EXTRACT (YEAR FROM DTPURCHASE))  ANO
FROM FORD.INDIVIDUAL I
INNER JOIN FORD.VEHICLERELATIONSHIP VR
ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER
INNER JOIN FORD.VEHICLEFACT VF
ON VR.IDVEHICLE = VF.IDVEHICLE
INNER JOIN FORD.VEHICLE V
ON VF.IDVEHICLE = V.IDVEHICLE
INNER JOIN FORD.MAKERMODEL MM
ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
INNER JOIN DIASW.DEPARA_DASH DP -- SELECT * FROM FORD.VEHICLERELATIONSHIP
ON VF.CDTMA = DP.CDTMA
WHERE VR.DTPURCHASE BETWEEN TO_DATE('01/08/2019','DD/MM/YYYY') AND TO_DATE('31/12/2025','DD/MM/YYYY')
AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
AND MM.DSMAKER = 'FORD'
AND REPLACE(TRANSLATE(I.CPF, '1234567890', ' '),' ','') IS NULL 
AND NVL(I.CPF,'0')<>'0'
GROUP BY CAST(I.CPF AS NUMERIC);




-- CRIACAO TABELA TEMPORARIA PARA QUANTIDADE DE VEICULOS POR USUARIO
CREATE TABLE TMP_QTD_VEICULO_FORD_PASS AS
SELECT CAST(A.CPF AS NUMERIC) CPF
  ,COUNT(*) QT  
FROM STG_PROC_FORD_PASS_CADR A
WHERE REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL
GROUP BY CAST(A.CPF AS NUMERIC);
UPDATE STG_PROC_FORD_PASS_CADR 
SET CPF = REPLACE( REPLACE( CPF,'-',''),'.',''); COMMIT;


--CRIACAO DE TABELA TEMPORARIA PARA VERIFICAÇÃO DE REVISAO

CREATE TABLE TMP_REVISAO_FORD_PASS AS 
SELECT DISTINCT CAST(A.CPF AS NUMERIC) CPF
,A.CAPP03_VIN_C CHASSI 
FROM STG_PROC_FORD_PASS_CADR A 
INNER JOIN FORD.REVISION B
ON A.CAPP03_VIN_C = B.DSVIN
AND TO_DATE (B.DTREVISION,'DD/MM/YY') >= TO_DATE( A.CAPP04_CREATE_S,'YYYY-MM-DD')
WHERE REPLACE(TRANSLATE(A.CPF, '1234567890',' '),' ','') IS NULL;


--INSERT TABELA FINAL 


INSERT INTO TMP_PROC_FORD_PASS_TRAT--(USERID,FIRST_ACCESS,YM_FIRSTACESS,LASTACESS,YM_LASTACESS,STATUS_USER,USERTYPE,RECENCY,NAMEPLATE,CARS_BY_USER,MAINTANANCE,FIDELITY,CPF)
SELECT
A.CAPP01_USER_D_A
,TO_DATE(B.FIRST_TRANS,'YYYY-MM-DD')
,SUBSTR (B.FIRST_TRANS, 1, 7) AS YM_FIRSTACESS
,TO_DATE(B.LAST_TRANS,'MM/DD/YYYY')
,SUBSTR(B.LAST_TRANS,7,10)||'-'|| SUBSTR (B.LAST_TRANS, 1, 2)  AS YM_LASTACESS
,B.USERCAT01
,B.STAT01
,CASE WHEN TO_DATE('09/01/2019','MM/DD/YYYY') - TO_DATE(B.LAST_TRANS,'MM/DD/YYYY') <= 30             THEN 'ATÉ 30 DIAS'
      WHEN TO_DATE('09/01/2019','MM/DD/YYYY') - TO_DATE(B.LAST_TRANS,'MM/DD/YYYY') BETWEEN 31 AND 90 THEN 'ATÉ 30 A 90 DIAS'
      WHEN TO_DATE('09/01/2019','MM/DD/YYYY') - TO_DATE(B.LAST_TRANS,'MM/DD/YYYY') > 90              THEN 'MAIS DE 90 DIAS'
      END AS RECENCY
,A.CDRV03_LCL_MDL_N
,CASE  
    WHEN C.QT = 1 THEN 'ONE'
    WHEN C.QT = 2 THEN 'TWO'
    WHEN C.QT = 3 THEN 'THREE'
    WHEN C.QT = 4 THEN 'FOUR'
    WHEN C.QT >= 5 THEN 'MORE THEN FIVE'
    END AS CARS_BY_USER                                                                       
,CASE WHEN D.CPF IS NOT NULL THEN 'Y' 
      WHEN D.CPF IS NULL THEN 'N'
      END AS MAINTANANCE
,CASE  
    WHEN EXTRACT (YEAR FROM SYSDATE) - E.ANO <= 1 THEN 'ONE YEAR'
    WHEN EXTRACT (YEAR FROM SYSDATE) - E.ANO = 2 THEN 'TWO YEARS'
    WHEN EXTRACT (YEAR FROM SYSDATE) - E.ANO = 3 THEN 'THREE YEARS'
    WHEN EXTRACT (YEAR FROM SYSDATE) - E.ANO = 4 THEN 'FOUR YEARS'
    WHEN EXTRACT (YEAR FROM SYSDATE) - E.ANO >= 5 THEN 'MORE THEN FIVE YEARS' 
     END AS FIDELITY
 ,A.CPF 
-- SELECT COUNT(*)
FROM STG_PROC_FORD_PASS_CADR A -- SELECT COUNT(*) FROM STG_PROC_FORD_PASS_CADR
INNER JOIN STG_PROC_FORD_PASS_ACES B 
ON UPPER(A.CAPP01_USER_D_A) = UPPER(B.GUID)
INNER JOIN TMP_QTD_VEICULO_FORD_PASS C
ON A.CPF = C.CPF
LEFT JOIN TMP_REVISAO_FORD_PASS D
ON A.CAPP03_VIN_C = D.CHASSI
INNER JOIN TMP_TEMPO_CASA_FORD_PASS E
ON A.CPF = E.CPF;


-- LIMPEZA DE ESTRUTURAS TEMPORARIAS/VALIDACOES DE LINHAS 

DELETE FROM STG_PROC_FORD_PASS_CADR
WHERE CPF = 'NULL';

DROP TABLE TMP_REVISAO_FORD_PASS;

DROP TABLE TMP_TEMPO_CASA_FORD_PASS;

DROP TABLE TMP_QTD_VEICULO_FORD_PASS;

SELECT * FROM TMP_PROC_FORD_PASS_TRAT