--Extração e criação Oracle 
CREATE TABLE TMP_EXTR_GLOBO AS
SELECT A.DS_NOME
      ,A.DS_MAIL
      ,A.DS_CIDD
      ,A.DS_UF
      ,B.DS_MODL_RESM
      ,ROW_NUMBER() OVER(PARTITION BY A.DS_MAIL ORDER BY TO_DATE(B.DT_COMP,'DD/MM/YY') DESC) NR_SEQC
FROM TAB_PROC_DBM_CLIE_UNIF A 
INNER JOIN TAB_PROC_DBM_TRAN B
ON A.NR_CPF = B.NR_CPF
WHERE TO_DATE(B.DT_COMP,'DD/MM/YY') BETWEEN TO_DATE('01/01/18','DD/MM/YY') AND TO_DATE('31/12/20','DD/MM/YY')
;COMMIT;

DROP TABLE TAB_PROC_EXTR_GLOBO;COMMIT;
CREATE TABLE TAB_PROC_EXTR_GLOBO AS 
SELECT DS_NOME
      ,DS_MAIL
      ,DS_CIDD
      ,DS_UF
      ,DS_MODL_RESM
FROM TMP_EXTR_GLOBO
WHERE NR_SEQC = 1
;COMMIT;

DROP TABLE TMP_EXTR_GLOBO; COMMIT;


-- Criação tabela SQL Server




BEGIN TRAN
DROP TABLE TAB_PROC_EXTR_GLOBO
COMMIT TRAN

SELECT  convert(varchar(500),HASHBYTES('SHA2_256',LOWER(DS_MAIL)),2) as email
	   ,DS_CIDD  as cidade
	   ,DS_UF as estado
	   ,DS_MODL_RESM as nameplate
INTO TAB_PROC_EXTR_GLOBO
FROM TMP_EXTR_GLOBO


