INSERT INTO TAB_PROC_ETL_FCSD_VEI
SELECT VR.IDVEHICLEHOLDER
,VR.IDVEHICLE
,VR.DTPURCHASE
,CASE WHEN VR.IDDEALER = '999999999' THEN TO_NUMBER(VF.IDDEALERDELIVER) ELSE VR.IDDEALER END AS IDDEALER
,VF.CDTMA
FROM FORD.VEHICLERELATIONSHIP VR
,FORD.VEHICLEFACT VF
WHERE VR.IDVEHICLE = VF.IDVEHICLE
AND VR.FLFIRSTOWNER = 'S'
AND VR.DTPURCHASE BETWEEN TO_DATE(ADD_MONTHS(SYSDATE,-36),'DD/MM/YY') AND TO_DATE(SYSDATE,'DD/MM/YY')
AND VF.CDTMA IN ('EUA','EEF','FHC','FFC','BHC','BFC','FFA','BDA','GDA','FAD','NFB','BFA','NFA','6BC','7BC','6BB','7BB','BUA','CHC','CFA','FFB','KHC','KFA','2BC','4BC','3BB','4BB','EMA')

;COMMIT;

--Insert - Tabela FCSD

INSERT INTO TAB_PROC_ETL_FCSD
SELECT VR.IDVEHICLEHOLDER
,VR.IDVEHICLE
,MD.DTPURCHASE
,VR.DTPURCHASE AS DTPURCHASE_UCC
,CASE WHEN MD.IDDEALER = '999999999' THEN TO_NUMBER(VF.IDDEALERDELIVER) ELSE MD.IDDEALER END AS IDDEALER
,MM.DSORIGINALMODEL
,V.NBMODELYEAR
,MM.DSMAKER
,MM.DSMODEL
,MM.DSGENERICMODEL
,MM.DSCATEGORY
,MM.DSSEGMENT
,VF.DSVIN
,VF.CDTMA
,D.NMDEALER
,ROUND(MONTHS_BETWEEN(SYSDATE,VR.DTPURCHASE))TEMPO
FROM FORD.VEHICLE V
,TAB_PROC_ETL_FCSD_VEI MD
,FORD.VEHICLERELATIONSHIP VR
,FORD.VEHICLEFACT VF
,FORD.MAKERMODEL MM
,FORD.DEALER D
WHERE V.IDVEHICLE = VR.IDVEHICLE
AND V.IDVEHICLE = VF.IDVEHICLE
AND MD.IDVEHICLE = VR.IDVEHICLE
AND V.DSORIGINALMODEL = MM.DSORIGINALMODEL
AND VR.IDDEALER = D.IDDEALER(+)
AND VR.FLSTILLOWNED = 'S'
AND VR.DTPURCHASE BETWEEN TO_DATE(ADD_MONTHS(SYSDATE,-36),'DD/MM/YY') AND TO_DATE(SYSDATE,'DD/MM/YY')
AND VF.CDTMA IN ('EUA','EEF','FHC','FFC','BHC','BFC','FFA','BDA','GDA','FAD','NFB','BFA','NFA','6BC','7BC','6BB','7BB','BUA','CHC','CFA','FFB','KHC','KFA','2BC','4BC','3BB','4BB','EMA')

;COMMIT;

--Insert - FCSD Até 2014

INSERT INTO TAB_PROC_ETL_FCSD_ATE2014
SELECT CDB.*
,T2.PRIMEIRA_REVISAO
,T2.IDDEALER_PRIMEIRA_REVISAO
,T2.NMDEALER_PRIMEIRA_REVISAO
,T2.SEGUNDA_REVISAO
,T2.IDDEALER_SEGUNDA_REVISAO
,T2.NMDEALER_SEGUNDA_REVISAO
,T2.TERCEIRA_REVISAO
,T2.IDDEALER_TERCEIRA_REVISAO
,T2.NMDEALER_TERCEIRA_REVISAO
,T2.QUARTA_REVISAO
,T2.IDDEALER_QUARTA_REVISAO
,T2.NMDEALER_QUARTA_REVISAO
,T2.QUINTA_REVISAO
,T2.IDDEALER_QUINTA_REVISAO
,T2.NMDEALER_QUINTA_REVISAO
,T2.SEXTA_REVISAO
,T2.IDDEALER_SEXTA_REVISAO
,T2.NMDEALER_SEXTA_REVISAO
,ADD_MONTHS(DTPURCHASE,6)AS PREVISAO_PRIMEIRA_REVISAO,
    CASE WHEN T2.PRIMEIRA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,6),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_1,
    ADD_MONTHS(DTPURCHASE,12)AS PREVISAO_SEGUNDA_REVISAO,
    CASE WHEN T2.SEGUNDA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,12),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_2,
    ADD_MONTHS(DTPURCHASE,18)AS PREVISAO_TERCEIRA_REVISAO,
    CASE WHEN T2.TERCEIRA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,18),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_3,
    ADD_MONTHS(DTPURCHASE,24)AS PREVISAO_QUARTA_REVISAO,
    CASE WHEN T2.QUARTA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,24),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_4,
    ADD_MONTHS(DTPURCHASE,30)AS PREVISAO_QUINTA_REVISAO,
    CASE WHEN T2.QUINTA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,30),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_5,
    ADD_MONTHS(DTPURCHASE,36)AS PREVISAO_SEXTA_REVISAO,
    CASE WHEN T2.SEXTA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,36),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_6
,'1' CHAVE_1
,'2' CHAVE_2
,'3' CHAVE_3
,'4' CHAVE_4
,'5' CHAVE_5
,'6' CHAVE_6
,NULL MAX_PREV_REV_1
,NULL MAX_PREV_REV_2
,NULL MAX_PREV_REV_3
,NULL MAX_PREV_REV_4
,NULL MAX_PREV_REV_5
,NULL MAX_PREV_REV_6
,NULL MIN_PREV_REV_1
,NULL MIN_PREV_REV_2
,NULL MIN_PREV_REV_3
,NULL MIN_PREV_REV_4
,NULL MIN_PREV_REV_5
,NULL MIN_PREV_REV_6
FROM TAB_PROC_ETL_FCSD CDB,
(
SELECT DSVIN
,MAX(DECODE(RANK_REV,1,DTREVISION,null)) PRIMEIRA_REVISAO
,MAX(DECODE(RANK_REV,1,IDDEALER_REV,null)) IDDEALER_PRIMEIRA_REVISAO    
,MAX(DECODE(RANK_REV,1,NMDEALER_REV,null)) NMDEALER_PRIMEIRA_REVISAO  
,MAX(DECODE(RANK_REV,2,DTREVISION,null)) SEGUNDA_REVISAO
,MAX(DECODE(RANK_REV,2,IDDEALER_REV,null)) IDDEALER_SEGUNDA_REVISAO
,MAX(DECODE(RANK_REV,2,NMDEALER_REV,null)) NMDEALER_SEGUNDA_REVISAO
,MAX(DECODE(RANK_REV,3,DTREVISION,null)) TERCEIRA_REVISAO
,MAX(DECODE(RANK_REV,3,IDDEALER_REV,null)) IDDEALER_TERCEIRA_REVISAO
,MAX(DECODE(RANK_REV,3,NMDEALER_REV,null)) NMDEALER_TERCEIRA_REVISAO
,MAX(DECODE(RANK_REV,4,DTREVISION,null)) QUARTA_REVISAO
,MAX(DECODE(RANK_REV,4,IDDEALER_REV,null)) IDDEALER_QUARTA_REVISAO   
,MAX(DECODE(RANK_REV,4,NMDEALER_REV,null)) NMDEALER_QUARTA_REVISAO   
,MAX(DECODE(RANK_REV,5,DTREVISION,null)) QUINTA_REVISAO
,MAX(DECODE(RANK_REV,5,IDDEALER_REV,null)) IDDEALER_QUINTA_REVISAO 
,MAX(DECODE(RANK_REV,5,NMDEALER_REV,null)) NMDEALER_QUINTA_REVISAO 
,MAX(DECODE(RANK_REV,6,DTREVISION,null)) SEXTA_REVISAO
,MAX(DECODE(RANK_REV,6,IDDEALER_REV,null)) IDDEALER_SEXTA_REVISAO
,MAX(DECODE(RANK_REV,6,NMDEALER_REV,null)) NMDEALER_SEXTA_REVISAO
FROM (SELECT REV.DSVIN
,TO_NUMBER(REV.TPREVISION) AS TPREVISION
,REV.DTREVISION
,REV.IDDEALER AS IDDEALER_REV
,D.NMDEALER AS NMDEALER_REV
,RANK() OVER(PARTITION BY DSVIN ORDER BY TO_NUMBER(REV.TPREVISION)) RANK_REV 
FROM FORD.REVISION REV
,FORD.DEALER D
WHERE REV.TPREVISION IN ('01','1','02','2','03','3','04','4','05','5','06','6')
AND REV.IDDEALER = D.IDDEALER(+))REV
GROUP BY REV.DSVIN ) T2
WHERE CDB.DSVIN = T2.DSVIN(+)
AND NBMODELYEAR <= 2014

;COMMIT;

--Insert - FCSD Até 2014 / Datas

INSERT INTO TAB_PROC_FCSD_ATE2014_DATAS
SELECT 1 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_PRIMEIRA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_PRIMEIRA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_ATE2014
UNION ALL

SELECT 2 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_SEGUNDA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_SEGUNDA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_ATE2014
UNION ALL

SELECT 3 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_TERCEIRA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_TERCEIRA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_ATE2014
UNION ALL

SELECT 4 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_QUARTA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_QUARTA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_ATE2014
UNION ALL

SELECT 5 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_QUINTA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_QUINTA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV
FROM TAB_PROC_ETL_FCSD_ATE2014
UNION ALL

SELECT 6 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_SEXTA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_SEXTA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_ATE2014
;COMMIT;

--UPDATE_MAX_PREV_REV 2014

--update - chave_1
UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MAX_PREV_REV_1 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
;COMMIT;

--update - chave_2
UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MAX_PREV_REV_2 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
;COMMIT;

--update - chave_3

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MAX_PREV_REV_3 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
;COMMIT;

--update - chave_4

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MAX_PREV_REV_4 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
;COMMIT;

--update - chave_5

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MAX_PREV_REV_5 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_5 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_5 = BB.CHAVE)
;COMMIT;

--update - chave_6


UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MAX_PREV_REV_6 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_6 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_6 = BB.CHAVE)
;COMMIT;

--2014 Update - MIN / Prev. Rev.

--update - chave_1

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MIN_PREV_REV_1 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
;COMMIT;

--update - chave_2

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MIN_PREV_REV_2 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
;COMMIT;

--update - chave_3

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MIN_PREV_REV_3 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
;COMMIT;

--update - chave_4

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MIN_PREV_REV_4 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
;COMMIT;

--update - chave_5

UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MIN_PREV_REV_5 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_5 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_5 = BB.CHAVE)
;COMMIT;

--update - chave_6


UPDATE TAB_PROC_ETL_FCSD_ATE2014 AA SET AA.MIN_PREV_REV_6 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_6 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_ATE2014_DATAS BB WHERE AA.CHAVE_6 = BB.CHAVE)
;COMMIT;

--Insert - FCSD 2015

INSERT INTO TAB_PROC_ETL_FCSD_2015
SELECT CDB.*
,T2.PRIMEIRA_REVISAO
,T2.IDDEALER_PRIMEIRA_REVISAO
,T2.NMDEALER_PRIMEIRA_REVISAO
,T2.SEGUNDA_REVISAO
,T2.IDDEALER_SEGUNDA_REVISAO
,T2.NMDEALER_SEGUNDA_REVISAO
,T2.TERCEIRA_REVISAO
,T2.IDDEALER_TERCEIRA_REVISAO
,T2.NMDEALER_TERCEIRA_REVISAO
,T2.QUARTA_REVISAO
,T2.IDDEALER_QUARTA_REVISAO
,T2.NMDEALER_QUARTA_REVISAO
,ADD_MONTHS(DTPURCHASE,6)AS PREVISAO_PRIMEIRA_REVISAO
    ,CASE WHEN T2.PRIMEIRA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,6),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_1
    ,ADD_MONTHS(DTPURCHASE,12)AS PREVISAO_SEGUNDA_REVISAO
    ,CASE WHEN T2.SEGUNDA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,12),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_2
    ,ADD_MONTHS(DTPURCHASE,24)AS PREVISAO_TERCEIRA_REVISAO
    ,CASE WHEN T2.TERCEIRA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,24),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_3
    ,ADD_MONTHS(DTPURCHASE,36)AS PREVISAO_QUARTA_REVISAO
    ,CASE WHEN T2.QUARTA_REVISAO <= LAST_DAY(ADD_MONTHS(ADD_MONTHS(CDB.DTPURCHASE,36),1)) THEN 'S' ELSE 'N' END AS REV_REALIZADA_4
,'1' CHAVE_1
,'2' CHAVE_2
,'3' CHAVE_3
,'4' CHAVE_4
,NULL MAX_PREV_REV_1
,NULL MAX_PREV_REV_2
,NULL MAX_PREV_REV_3
,NULL MAX_PREV_REV_4
,NULL MIN_PREV_REV_1
,NULL MIN_PREV_REV_2
,NULL MIN_PREV_REV_3
,NULL MIN_PREV_REV_4
FROM TAB_PROC_ETL_FCSD CDB,
(
SELECT DSVIN
,MAX(DECODE(RANK_REV,1,DTREVISION,null)) PRIMEIRA_REVISAO
,MAX(DECODE(RANK_REV,1,IDDEALER_REV,null)) IDDEALER_PRIMEIRA_REVISAO 
,MAX(DECODE(RANK_REV,1,NMDEALER_REV,null)) NMDEALER_PRIMEIRA_REVISAO
,MAX(DECODE(RANK_REV,2,DTREVISION,null)) SEGUNDA_REVISAO
,MAX(DECODE(RANK_REV,2,IDDEALER_REV,null)) IDDEALER_SEGUNDA_REVISAO
,MAX(DECODE(RANK_REV,2,NMDEALER_REV,null)) NMDEALER_SEGUNDA_REVISAO
,MAX(DECODE(RANK_REV,3,DTREVISION,null)) TERCEIRA_REVISAO
,MAX(DECODE(RANK_REV,3,IDDEALER_REV,null)) IDDEALER_TERCEIRA_REVISAO 
,MAX(DECODE(RANK_REV,3,NMDEALER_REV,null)) NMDEALER_TERCEIRA_REVISAO
,MAX(DECODE(RANK_REV,4,DTREVISION,null)) QUARTA_REVISAO
,MAX(DECODE(RANK_REV,4,IDDEALER_REV,null)) IDDEALER_QUARTA_REVISAO   
,MAX(DECODE(RANK_REV,4,NMDEALER_REV,null)) NMDEALER_QUARTA_REVISAO        
FROM (SELECT REV.DSVIN
,TO_NUMBER(REV.TPREVISION) TPREVISION
,REV.DTREVISION
,REV.IDDEALER AS IDDEALER_REV
,D.NMDEALER AS NMDEALER_REV
,RANK() OVER(PARTITION BY DSVIN ORDER BY TO_NUMBER(REV.TPREVISION)) RANK_REV 
FROM FORD.REVISION REV
,FORD.DEALER D
WHERE REV.TPREVISION IN ('01','1','02','2','04','4','06','6')
AND REV.IDDEALER = D.IDDEALER(+))REV
GROUP BY REV.DSVIN) T2
WHERE CDB.DSVIN = T2.DSVIN(+)
AND NBMODELYEAR > 2014
;COMMIT;

--Insert - FCSD 2015 / Datas

INSERT INTO TAB_PROC_FCSD_2015_DATAS
SELECT 1 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_PRIMEIRA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_PRIMEIRA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_2015
UNION ALL
SELECT 2 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_SEGUNDA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_SEGUNDA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV
FROM TAB_PROC_ETL_FCSD_2015
UNION ALL
SELECT 3 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_TERCEIRA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_TERCEIRA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_2015
UNION ALL
SELECT 4 AS CHAVE
,LAST_DAY(MAX(TO_DATE(PREVISAO_QUARTA_REVISAO,'DD/MM/YYYY'))) AS MAX_PREV_REV
,MIN(TO_DATE(PREVISAO_QUARTA_REVISAO,'DD/MM/YYYY')) AS MIN_PREV_REV 
FROM TAB_PROC_ETL_FCSD_2015
;COMMIT;

--2015 Update - MAX / Prev. Rev.

--update - chave_1

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MAX_PREV_REV_1 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
;COMMIT;

--update - chave_2

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MAX_PREV_REV_2 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
;COMMIT;

--update - chave_3

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MAX_PREV_REV_3 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
;COMMIT;

--update-chave_4

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MAX_PREV_REV_4 = (SELECT BB.MAX_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
;COMMIT;


--2015 Update - MIN / Prev. Rev.

--update - chave_1

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MIN_PREV_REV_1 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_1 = BB.CHAVE)
;COMMIT;

--update - chave_2

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MIN_PREV_REV_2 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_2 = BB.CHAVE)
;COMMIT;

--update - chave_3

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MIN_PREV_REV_3 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_3 = BB.CHAVE)
;COMMIT;

--update - chave_4

UPDATE TAB_PROC_ETL_FCSD_2015 AA SET AA.MIN_PREV_REV_4 = (SELECT BB.MIN_PREV_REV FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
WHERE EXISTS (SELECT 1 FROM  TAB_PROC_FCSD_2015_DATAS BB WHERE AA.CHAVE_4 = BB.CHAVE)
;COMMIT;


--UNION - FCSD 2014

INSERT INTO TAB_PROC_ETL_FCSD_ATE2014_2
SELECT * FROM (
SELECT ASD.*,RANK()OVER(PARTITION BY IDVEHICLEHOLDER,DSVIN ORDER BY TO_DATE(MES,'DD/MM/YYYY') ASC)RANK_MES_ENVIO FROM (
-- 6 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_PRIMEIRA_REVISAO AS PREVISAO_REVISAO
,'6 MESES' AS "OFERTA"
,REV_REALIZADA_1 AS REV_REALIZADA
,IDDEALER_PRIMEIRA_REVISAO AS IDDEALER_REV
,PRIMEIRA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER ELSE IDDEALER_PRIMEIRA_REVISAO END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_PRIMEIRA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_ATE2014
WHERE TO_DATE(PREVISAO_PRIMEIRA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_1,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_1,'DD/MM/YYYY') 
AND PREVISAO_PRIMEIRA_REVISAO IS NOT NULL
UNION ALL
-- 12 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_SEGUNDA_REVISAO AS PREVISAO_REVISAO
,'12 MESES' AS "OFERTA"
,REV_REALIZADA_2 AS REV_REALIZADA
,IDDEALER_SEGUNDA_REVISAO AS IDDEALER_REV
,SEGUNDA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO ELSE IDDEALER_SEGUNDA_REVISAO END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_SEGUNDA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_ATE2014
WHERE TO_DATE(PREVISAO_SEGUNDA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_2,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_2,'DD/MM/YYYY')
AND PREVISAO_SEGUNDA_REVISAO IS NOT NULl
UNION ALL


-- 18 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_TERCEIRA_REVISAO AS PREVISAO_REVISAO
,'18 MESES' AS "OFERTA"
,REV_REALIZADA_3 AS REV_REALIZADA
,IDDEALER_TERCEIRA_REVISAO AS IDDEALER_REV
,TERCEIRA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO
      WHEN IDDEALER_TERCEIRA_REVISAO IS NULL THEN IDDEALER_SEGUNDA_REVISAO ELSE IDDEALER_TERCEIRA_REVISAO 
      END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_TERCEIRA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_ATE2014
WHERE TO_DATE(PREVISAO_TERCEIRA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_3,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_3,'DD/MM/YYYY')
AND PREVISAO_TERCEIRA_REVISAO IS NOT NULL
UNION ALL


-- 24 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_QUARTA_REVISAO AS PREVISAO_REVISAO
,'24 MESES' AS "OFERTA"
,REV_REALIZADA_4 AS REV_REALIZADA
,IDDEALER_QUARTA_REVISAO AS IDDEALER_REV
,QUARTA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO
      WHEN IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL THEN IDDEALER_SEGUNDA_REVISAO
      WHEN IDDEALER_QUARTA_REVISAO IS NULL THEN IDDEALER_TERCEIRA_REVISAO ELSE IDDEALER_QUARTA_REVISAO END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_QUARTA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_ATE2014
WHERE TO_DATE(PREVISAO_QUARTA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_4,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_4,'DD/MM/YYYY')
AND PREVISAO_QUARTA_REVISAO IS NOT NULL
UNION ALL


-- 30 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_QUINTA_REVISAO AS PREVISAO_REVISAO
,'30 MESES' AS "OFERTA"
,REV_REALIZADA_5 AS REV_REALIZADA
,IDDEALER_QUINTA_REVISAO AS IDDEALER_REV
,QUINTA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO
      WHEN IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL THEN IDDEALER_SEGUNDA_REVISAO
      WHEN IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL THEN IDDEALER_TERCEIRA_REVISAO
      WHEN IDDEALER_QUINTA_REVISAO IS NULL THEN IDDEALER_QUARTA_REVISAO ELSE IDDEALER_QUINTA_REVISAO END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_QUINTA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_ATE2014 
WHERE TO_DATE(PREVISAO_QUINTA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_5,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_5,'DD/MM/YYYY') 
AND PREVISAO_QUINTA_REVISAO IS NOT NULL
UNION ALL


-- 36 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_SEXTA_REVISAO AS PREVISAO_REVISAO
,'36 MESES' AS "OFERTA"
,REV_REALIZADA_6 AS REV_REALIZADA
,IDDEALER_SEXTA_REVISAO AS IDDEALER_REV
,SEXTA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_SEXTA_REVISAO IS NULL AND IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_SEXTA_REVISAO IS NULL AND IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO
      WHEN IDDEALER_SEXTA_REVISAO IS NULL AND IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL THEN IDDEALER_SEGUNDA_REVISAO
      WHEN IDDEALER_SEXTA_REVISAO IS NULL AND IDDEALER_QUINTA_REVISAO IS NULL AND IDDEALER_QUARTA_REVISAO IS NULL THEN IDDEALER_TERCEIRA_REVISAO
      WHEN IDDEALER_SEXTA_REVISAO IS NULL AND IDDEALER_QUINTA_REVISAO IS NULL THEN IDDEALER_QUARTA_REVISAO
      WHEN IDDEALER_SEXTA_REVISAO IS NULL THEN IDDEALER_QUINTA_REVISAO ELSE IDDEALER_SEXTA_REVISAO 
      END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_SEXTA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_ATE2014 
WHERE TO_DATE(PREVISAO_SEXTA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_6,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_6,'DD/MM/YYYY')
AND PREVISAO_SEXTA_REVISAO IS NOT NULL
)ASD WHERE ASD.REV_REALIZADA = 'N'
)WHERE RANK_MES_ENVIO = 1

;COMMIT;

--UNION - FCSD 2015

INSERT INTO TAB_PROC_ETL_FCSD_2015_2
SELECT * FROM (
SELECT ASD.*,RANK()OVER(PARTITION BY IDVEHICLEHOLDER,DSVIN ORDER BY TO_DATE(MES,'DD/MM/YYYY') ASC)RANK_MES_ENVIO FROM (
-- 6 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_PRIMEIRA_REVISAO AS PREVISAO_REVISAO
,'6 MESES' AS "OFERTA"
,REV_REALIZADA_1 AS REV_REALIZADA
,IDDEALER_PRIMEIRA_REVISAO AS IDDEALER_REV
,PRIMEIRA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER ELSE IDDEALER_PRIMEIRA_REVISAO END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_PRIMEIRA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_2015 
WHERE TO_DATE(PREVISAO_PRIMEIRA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_4,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_4,'DD/MM/YYYY') 
AND PREVISAO_PRIMEIRA_REVISAO IS NOT NULL
UNION ALL
-- 12 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_SEGUNDA_REVISAO AS PREVISAO_REVISAO
,'12 MESES' AS "OFERTA"
,REV_REALIZADA_2 AS REV_REALIZADA
,IDDEALER_SEGUNDA_REVISAO AS IDDEALER_REV
,SEGUNDA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO ELSE IDDEALER_SEGUNDA_REVISAO 
      END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_SEGUNDA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_2015
WHERE TO_DATE(PREVISAO_SEGUNDA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_4,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_4,'DD/MM/YYYY')
AND PREVISAO_SEGUNDA_REVISAO IS NOT NULL
UNION ALL
-- 24 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_TERCEIRA_REVISAO AS PREVISAO_REVISAO
,'24 MESES' AS "OFERTA"
,REV_REALIZADA_3 AS REV_REALIZADA
,IDDEALER_TERCEIRA_REVISAO AS IDDEALER_REV
,TERCEIRA_REVISAO AS REVISAO
,IDVEHICLE
,CASE WHEN IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO
      WHEN IDDEALER_TERCEIRA_REVISAO IS NULL THEN IDDEALER_SEGUNDA_REVISAO ELSE IDDEALER_TERCEIRA_REVISAO END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_TERCEIRA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_2015 WHERE TO_DATE(PREVISAO_TERCEIRA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_4,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_4,'DD/MM/YYYY')
AND PREVISAO_TERCEIRA_REVISAO IS NOT NULL
UNION ALL
-- 36 MESES
SELECT IDVEHICLEHOLDER
,DSVIN
,IDDEALER
,CDTMA
,DTPURCHASE
,PREVISAO_QUARTA_REVISAO AS PREVISAO_REVISAO
,'36 MESES' AS "OFERTA"
,REV_REALIZADA_4 AS REV_REALIZADA
,IDDEALER_QUARTA_REVISAO AS IDDEALER_REV
,QUARTA_REVISAO AS REVISAO,IDVEHICLE
,CASE WHEN IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL AND IDDEALER_PRIMEIRA_REVISAO IS NULL THEN IDDEALER
      WHEN IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL AND IDDEALER_SEGUNDA_REVISAO IS NULL THEN IDDEALER_PRIMEIRA_REVISAO
      WHEN IDDEALER_QUARTA_REVISAO IS NULL AND IDDEALER_TERCEIRA_REVISAO IS NULL THEN IDDEALER_SEGUNDA_REVISAO
      WHEN IDDEALER_QUARTA_REVISAO IS NULL THEN IDDEALER_TERCEIRA_REVISAO ELSE IDDEALER_QUARTA_REVISAO END AS IDDEALER_REV_RESP
,TO_CHAR(TRUNC(PREVISAO_QUARTA_REVISAO,'MM'),'DD/MM/YYYY') AS MES
FROM TAB_PROC_ETL_FCSD_2015 WHERE TO_DATE(PREVISAO_QUARTA_REVISAO,'DD/MM/YYYY') BETWEEN TO_DATE(MIN_PREV_REV_4,'DD/MM/YYYY') AND TO_DATE(MAX_PREV_REV_4,'DD/MM/YYYY') 
AND PREVISAO_QUARTA_REVISAO IS NOT NULL
)ASD WHERE ASD.REV_REALIZADA = 'N'
)WHERE RANK_MES_ENVIO = 1
;COMMIT;

--Union - Visões 2014 e 2015

DROP TABLE TAB_PROC_ETL_FCSD_2;COMMIT;
CREATE TABLE TAB_PROC_ETL_FCSD_2 AS
SELECT AA.*,'ATE 2014' AS ANO_CARROS
FROM TAB_PROC_ETL_FCSD_ATE2014_2 AA WHERE REV_REALIZADA = 'N'
AND IDDEALER_REV_RESP IS NOT NULL
UNION ALL
SELECT AA.*,'2015' AS ANO_CARROS 
FROM TAB_PROC_ETL_FCSD_2015_2 AA 
WHERE REV_REALIZADA = 'N' 
AND IDDEALER_REV_RESP IS NOT NULL
;COMMIT;

ALTER TABLE TAB_PROC_ETL_FCSD_2 ADD FLOPTIN VARCHAR2(255)
;COMMIT;


--Update - Marcação de Optin

UPDATE TAB_PROC_ETL_FCSD_2 SET FLOPTIN = 'N'
WHERE IDVEHICLEHOLDER IN (SELECT IDPERSON FROM FORD.SPECIALHANDLINGFLAGS WHERE FLPERMISSION IN ('0','N'))
;COMMIT;

UPDATE TAB_PROC_ETL_FCSD_2 SET FLOPTIN = 'S'
WHERE FLOPTIN IS NULL;
;COMMIT;

DELETE FROM TAB_PROC_ETL_FCSD_2 WHERE FLOPTIN = 'N'
;COMMIT;



--Insert - Adicionando E-mails na Tabela


INSERT INTO TAB_PROC_ETL_FCSD_3
SELECT ASD.*
,BSD.IDEMAIL
,BSD.DSEMAIL
,NULL PURGE_EMAIL
,NULL ERROS_VT
,NULL TPPERSON
FROM TAB_PROC_ETL_FCSD_2 ASD,
(
SELECT MA.*
,EM.IDEMAIL
,EM.DSEMAIL
FROM (SELECT DISTINCT IDVEHICLEHOLDER FROM TAB_PROC_ETL_FCSD_2) MA
,(SELECT EM.*, RANK() OVER(PARTITION BY IDPERSON ORDER BY DTLASTUPDATE DESC, IDEMAIL DESC) RANK_EM
FROM FORD.EMAIL EM
WHERE CDNIXIETYPE IS NULL
AND FLUSEROW = 'S') EM      
WHERE MA.IDVEHICLEHOLDER = EM.IDPERSON(+)
AND EM.RANK_EM(+) = 1 )BSD
WHERE ASD.IDVEHICLEHOLDER = BSD.IDVEHICLEHOLDER(+)
AND BSD.DSEMAIL IS NOT NULL
;COMMIT;



-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--TABELAS NA QUERY

--TABELAS TRUNCADAS
ETL_FCSD_ATE2014_DATAS --TAB_PROC_ETL_FCSD_ATE2014_DATAS
ETL_FCSD_ATE2014--TAB_PROC_ETL_FCSD_ATE2014
ETL_FCSD--TAB_PROC_ETL_FCSD
ETL_FCSD_VEI --TAB_PROC_ETL_FCSD_VEI
ETL_FCSD_2015--TAB_PROC_ETL_FCSD_2015
ETL_FCSD_2015_DATAS--TAB_PROC_ETL_FCSD_2015_DATAS
ETL_FCSD_2--TAB_PROC_ETL_FCSD_2--------------
ETL_FCSD_3--TAB_PROC_ETL_FCSD_3
ETL_FCSD_ATE2014_2--TAB_PROC_ETL_FCSD_ATE2014_2
ETL_FCSD_2015_2 --TAB_PROC_ETL_FCSD_2015_2


--TABELAS FORD
FORD.PERSON
FORD.VEHICLERELATIONSHIP
FORD.VEHICLEFACT
FORD.MAKERMODEL
FORD.DEALER
FORD.REVISION
FORD.EMAIL
FORD.SPECIALHANDLINGFLAGS
FORD.VEHICLE
