DELETE FROM TMP_PESQUISA_POS_LEAD WHERE CPF IS NULL OR REPLACE(TRANSLATE(CPF, '1234567890', ' '),' ','') IS NOT NULL

CREATE TABLE TMP_PESQUISA_LEAD_COMPRA AS
SELECT CAST (I.CPF AS NUMERIC) CPF
,I.DT_CRIACAO AS DT_CADASTRO
,A.DT_COMP 
,A.MODELO_BIA AS MODELO
,I.LEAD_ID
,ROW_NUMBER() OVER(PARTITION BY I.LEAD_ID ORDER BY A.DT_COMP DESC) NR_SEQC
FROM TMP_PESQUISA_POS_LEAD I 
INNER JOIN TMP_PROC_DBM_VEIC A
ON I.CPF = CAST (A.NR_CPF AS NUMERIC)
AND TO_DATE(A.DT_COMP,'DD/MM/YY') BETWEEN TO_DATE(I.DT_CRIACAO ,'MM/DD/YY') AND TO_DATE(I.DT_CRIACAO ,'MM/DD/YY') + 90   

CREATE TABLE TMP_ESTUDO_POS_LEAD AS 
SELECT CAST (I.CPF AS NUMERIC) CPF
,I.DT_CRIACAO AS DT_CADASTRO
,I.LEAD_ID
,A.DT_COMP
,A.MODELO
FROM TMP_PESQUISA_POS_LEAD I
LEFT JOIN TMP_PESQUISA_LEAD_COMPRA A
ON I.LEAD_ID = A.LEAD_ID

DELETE FROM TMP_PESQUISA_LEAD_COMPRA 
WHERE NR_SEQC <> 1

SELECT * FROM TMP_ESTUDO_POS_LEAD
------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE  TMP_LEADS_2019_ESTUDO AS
SELECT DISTINCT CAST (I.CPF AS NUMERIC) CPF
,I.DATA_CRIACAO AS DT_LEAD
,A.DT_COMP 
,A.MODELO_BIA AS MODELO
,ROW_NUMBER() OVER(PARTITION BY I.CPF,I.DATA_CRIACAO ORDER BY I.DATA_CRIACAO DESC) NR_SEQC
FROM TAB_LEAD_TMP I 
INNER JOIN TMP_PROC_DBM_VEIC A
ON I.CPF = CAST (A.NR_CPF AS NUMERIC)
AND TO_DATE(A.DT_COMP,'DD/MM/YY') BETWEEN TO_DATE(I.DATA_CRIACAO ,'DD/MM/YY') AND TO_DATE(I.DATA_CRIACAO ,'DD/MM/YY') + 90   
WHERE I.DATA_CRIACAO BETWEEN TO_DATE('01/01/19','DD/MM/YY') AND TO_DATE('31/12/19','DD/MM/YY')


DELETE FROM TMP_LEADS_2019_ESTUDO 
WHERE NR_SEQC <> 1

SELECT * FROM TMP_LEADS_2019_ESTUDO
