  --VENDAS
SELECT COUNT(*), DT_COMP, ID_DEAL
  FROM TAB_PROC_DBM_TRAN
  WHERE DT_COMP>='01/01/20'
  GROUP BY DT_COMP, ID_DEAL
  ORDER BY 2,3


SELECT  DT_COMP,COUNT(*)
  FROM TAB_PROC_DBM_TRAN
  WHERE DT_COMP>='01/01/20'
  GROUP BY DT_COMP
  ORDER BY 1


SELECT ID_DEAL,COUNT(*)
  FROM TAB_PROC_DBM_TRAN
  WHERE DT_COMP>='01/01/20'
  GROUP BY ID_DEAL
  ORDER BY 1
 
--LEADS TOTAIS 
 SELECT COUNT(*)
      , CASE WHEN ORIGEM_DO_LEAD = 'Compre sem sair de casa' THEN 'Compre sem sair de casa'  ELSE 'WEB' END ORIGEM
      , TO_DATE(DATA_DE_CRIAÇÃO, 'DD/MM/YYYY')
   FROM   STG_PROC_LEAD_B A
   WHERE TO_DATE(DATA_DE_CRIAÇÃO, 'DD/MM/YYYY')
   GROUP BY CASE WHEN ORIGEM_DO_LEAD = 'Compre sem sair de casa'  THEN 'Compre sem sair de casa'  ELSE 'WEB' END
      , TO_DATE(DATA_DE_CRIAÇÃO, 'DD/MM/YYYY')
      ORDER BY 2,3 

 --SHEET LEAD CONVERTIDO

 SELECT *
   FROM (
   SELECT A.ORIGEM_DO_LEAD
        , SUB_ORIGEM
        , CATÁLOGO
        , TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY')
        , NOME_DA_CONCESSIONÁRIA
        , CPF
        , B.DT_COMP
        , B.DS_MODL
        , CD_CHAS
        , A.ID_PRINCIPAL
        , B.ID_DEAL
        , ROW_NUMBER() OVER(PARTITION BY CD_CHAS ORDER BY TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY') DESC)NRSEQC
   FROM   STG_PROC_LEAD_B A
   INNER JOIN TAB_PROC_DBM_TRAN B
     ON CAST(A.CPF AS NUMERIC) = B.NR_CPF
     AND B.DT_COMP BETWEEN TO_DATE(A.DATA_DE_CRIAÇÃO,'DD/MM/YYYY') AND TO_DATE(A.DATA_DE_CRIAÇÃO,'DD/MM/YYYY')+90
     WHERE REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL)
     WHERE NRSEQC = 1
     ORDER BY 4


 --LEADS CONVERTIDOS CONTAGEM
 SELECT COUNT(*), ORIGEM_DO_LEAD,DATA
   FROM (
   SELECT A.ORIGEM_DO_LEAD
        , SUB_ORIGEM
        , CATÁLOGO
        , TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY')DATA
        , NOME_DA_CONCESSIONÁRIA
        , CPF
        , B.DT_COMP
        , B.DS_MODL
        , ROW_NUMBER() OVER(PARTITION BY CD_CHAS ORDER BY TO_DATE(DATA_DE_CRIAÇÃO,'DD/MM/YYYY') DESC)NRSEQC
   FROM   STG_PROC_LEAD_B A
   INNER JOIN TAB_PROC_DBM_TRAN B
     ON CAST(A.CPF AS NUMERIC) = B.NR_CPF
     AND B.DT_COMP BETWEEN TO_DATE(A.DATA_DE_CRIAÇÃO,'DD/MM/YYYY') AND TO_DATE(A.DATA_DE_CRIAÇÃO,'DD/MM/YYYY')+90
     WHERE REPLACE(TRANSLATE(A.CPF, '1234567890', ' '),' ','') IS NULL)
     WHERE NRSEQC = 1
     GROUP BY ORIGEM_DO_LEAD,DATA
     ORDER BY 2,3 