SELECT A.NR_CPF         AS CPF
      ,A.DT_COMP        AS DT_COMP
      ,A.DS_MODL_ESPC   AS DS_MODL_ESPC
      ,B.DT_COMP        AS DT_COMP_ANTERIOR
      ,B.DS_MODL_ESPC   AS DS_MODL_ESPC_ANTERIOR
      ,CASE WHEN B.NR_CPF IS NULL THEN 'NAO' ELSE 'SIM' END  AS RECOMPRA
  FROM TAB_PROC_DBM_TRAN      A 
  LEFT JOIN TAB_PROC_DBM_TRAN B
    ON A.NR_CPF = B.NR_CPF 
    AND A.NR_SEQC+1 = B.NR_SEQC
  WHERE A.DT_COMP  BETWEEN SYSDATE AND SYSDATE -7




