-- oracle

DROP TABLE TMP_HIST_EMAIL_INTERE_ADOBE;COMMIT;
CREATE TABLE TMP_HIST_EMAIL_INTERE_ADOBE AS
SELECT A.EMAIL
      ,SUBSTR (A.DATE_SENT, 1, 10) AS DATA_ENVIO
      ,A.CAMPAIGN_CODE
      ,B.INTERACTION
      ,B.TYPE_INTE
      ,SUBSTR (B.INTE_DATE, 1, 10) AS DATE_INTERACAO
FROM TMP_HIST_ADOBE A
LEFT JOIN TMP_INTE_ADOBE B
 ON A.EMAIL = B.EMAIL
 ;COMMIT;

--sql server

 BEGIN TRAN
DROP TABLE STG_ADOB_INTR_ENVI
COMMIT TRAN


SELECT A.EMAIL
      ,SUBSTRING (A.DATE_SENT, 1, 10) AS DATA_ENVIO
      ,A.CAMPAIGN_CODE
      ,B.INTERACTION
      ,B.TYPE_INTE
      ,SUBSTRING (B.INTE_DATE, 1, 10) AS DATE_INTERACAO
INTO STG_ADOB_INTR_ENVI
FROM STG_ADOB_ENVI  A
LEFT JOIN STG_ADOB_INTR B
 ON A.EMAIL = B.EMAIL
