--TELEFONES PROSPECT

SELECT CAST (A.CPF AS NUMERIC) 
,A.*
,B.TELEPHONE_PREFIX||TELEPHONE_NUMBER
FROM TMP_MUSTANG_PROSPECTS A
INNER JOIN TMP_PROC_DBM_EXPE B
ON A.CPF = CAST(B.NR_CPF AS NUMERIC)
WHERE LENGTH(B.TELEPHONE_PREFIX) = 2
AND LENGTH(B.TELEPHONE_NUMBER) IN (8,9)
-- TELEFONE OWNERS MUSTANG

SELECT A.*
,B.IDVEHICLE
,C.IDINDIVIDUAL
,C.CPF
,D.NR_DDD_CELL||D.NR_CELL
--,D.TELEPHONE_PREFIX||TELEPHONE_NUMBER
FROM TMP_MUSTANG_OWNERS A
LEFT JOIN FORD.VEHICLERELATIONSHIP B
ON SUBSTR(A.NAVCODE_VEI,5,8)= B.IDVEHICLE
LEFT JOIN FORD.INDIVIDUAL C
ON B.IDVEHICLEHOLDER = C.IDINDIVIDUAL
LEFT JOIN TAB_PROC_DBM_CLIE_UNIF D
ON CAST (C.CPF AS NUMERIC) = D.NR_CPF
--LEFT JOIN TMP_PROC_DBM_EXPE D
--ON CAST (C.CPF AS NUMERIC) = CAST(D.NR_CPF AS NUMERIC)