SELECT * FROM FORD.VEHICLEFACT
 
SELECT VF.DSVIN,I.CPF,I.NMINDIVIDUAL,'PJ'
  FROM FORD.INDIVIDUAL               I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER 
 INNER JOIN FORD.VEHICLEFACT         VF
    ON VR.IDVEHICLE = VF.IDVEHICLE 
 INNER JOIN FORD.VEHICLE             V
    ON VF.IDVEHICLE = V.IDVEHICLE 
   WHERE (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
 
UNION
 
SELECT VF.DSVIN,I.CPF,I.NMINDIVIDUAL,'PF'
  FROM FORD.INDIVIDUAL               I
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER 
 INNER JOIN FORD.VEHICLEFACT         VF
    ON VR.IDVEHICLE = VF.IDVEHICLE 
 INNER JOIN FORD.VEHICLE             V
    ON VF.IDVEHICLE = V.IDVEHICLE 
   WHERE (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
