
 DROP TABLE TMP_V_TV;
 CREATE TABLE TMP_V_TV AS
SELECT DISTINCT CAST(I.CPF AS NUMERIC) CPF, CDTMA, CDSEQ, DTPURCHASE, DSVIN
  FROM FORD.INDIVIDUAL I 
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER 
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE 
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE 
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('04/10/2019','DD/MM/YYYY') AND TO_DATE('11/11/2019','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD';
   
 DROP TABLE TMP_V_TV_OWN;
 CREATE TABLE TMP_V_TV_OWN AS
SELECT DISTINCT CAST(I.CPF AS NUMERIC) CPF, CDTMA, CDSEQ, DTPURCHASE, DSVIN
  FROM FORD.INDIVIDUAL I 
 INNER JOIN FORD.VEHICLERELATIONSHIP VR
    ON I.IDINDIVIDUAL = VR.IDVEHICLEHOLDER 
 INNER JOIN FORD.VEHICLEFACT VF
    ON VR.IDVEHICLE = VF.IDVEHICLE 
 INNER JOIN FORD.VEHICLE V
    ON VF.IDVEHICLE = V.IDVEHICLE 
 INNER JOIN FORD.MAKERMODEL MM
    ON V.DSORIGINALMODEL = MM.DSORIGINALMODEL
 WHERE VR.DTPURCHASE BETWEEN TO_DATE('04/10/2010','DD/MM/YYYY') AND TO_DATE('04/10/2019','DD/MM/YYYY')
   AND (VR.IDDATASOURCE = 1 OR VR.IDCREATESOURCE = 1)
   AND MM.DSMAKER = 'FORD';
   
   
  
 
SELECT COUNT(DISTINCT DSVIN)
     , CASE WHEN CDSEQ = 'KCE9' THEN 'KA SE PLUS 1.0'
                WHEN CDSEQ = 'KNA9' THEN 'KA TITANIUM 1.5 AT'
                WHEN CDSEQ = 'KCE0' THEN 'KA SE Plus 1.0'
                WHEN CDSEQ = 'KCEM' THEN 'KA 100 ANOS 1.5 AT'
                WHEN CDSEQ = 'KCB0' THEN 'KA SE 1.0'
                WHEN CDSEQ = 'KDD0' THEN 'KA SE Plus 1.5 AT'
                WHEN CDSEQ = 'KFA0' THEN 'KA FreeStyle 1.0'
                WHEN CDSEQ = 'ZCB0' THEN 'KA Sedan'
                ELSE CDSEQ
             END
  FROM TAB_LEAD_THEVOICE A
  INNER JOIN TMP_V_TV B
  ON A.CPF = B.CPF
  group by CASE WHEN CDSEQ = 'KCE9' THEN 'KA SE PLUS 1.0'
                WHEN CDSEQ = 'KNA9' THEN 'KA TITANIUM 1.5 AT'
                WHEN CDSEQ = 'KCE0' THEN 'KA SE Plus 1.0'
                WHEN CDSEQ = 'KCEM' THEN 'KA 100 ANOS 1.5 AT'
                WHEN CDSEQ = 'KCB0' THEN 'KA SE 1.0'
                WHEN CDSEQ = 'KDD0' THEN 'KA SE Plus 1.5 AT'
                WHEN CDSEQ = 'KFA0' THEN 'KA FreeStyle 1.0'
                WHEN CDSEQ = 'ZCB0' THEN 'KA Sedan'
                ELSE CDSEQ
             END
  order by 1 DESC
  
  
SELECT COUNT(DISTINCT b.DSVIN)
     , case when c.cpf is null then 0
            when c.cpf is not null then 1
         end as flag_cpf
     , b.dtpurchase
  FROM TAB_LEAD_THEVOICE A
  INNER JOIN TMP_V_TV B
  ON A.CPF = B.CPF
  left join TMP_V_TV_OWN c
  on a.cpf = c.cpf
  group by case when c.cpf is null then 0
            when c.cpf is not null then 1
         end 
     , b.dtpurchase
  order by 3,2 DESC
  